"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ChevronDown, LayoutDashboard, LogOut, Mail, ShieldCheck, UserRound, X } from "lucide-react";
import type { Locale } from "@/lib/i18n";
import { captureConversion, conversionEvents, identifyUser, resetAnalyticsUser } from "@/lib/analytics";
import { AUTH_OPEN_EVENT, clearAuthSession, readAuthSession, saveAuthSession, type AuthSession } from "@/lib/client-auth";

type Session = AuthSession;
type Copy = { signIn:string; eyebrow:string; title:string; lead:string; email:string; send:string; sending:string; codeTitle:string; codeLead:string; code:string; verify:string; verifying:string; resend:string; success:string; signedIn:string; signOut:string; close:string; error:string };

const en: Copy = { signIn:"Sign in",eyebrow:"EMAIL SIGN-IN",title:"Welcome to FreeAIPPT",lead:"Enter your email and we'll send a secure 6-digit sign-in code.",email:"you@company.com",send:"Send code",sending:"Sending…",codeTitle:"Check your inbox",codeLead:"Enter the 6-digit code sent to",code:"6-digit code",verify:"Verify and sign in",verifying:"Verifying…",resend:"Use another email",success:"You're signed in.",signedIn:"Signed in as",signOut:"Sign out",close:"Close",error:"Something went wrong. Please try again." };
const copy: Record<Locale,Copy> = {
  en,
  "zh-CN":{...en,signIn:"登录",eyebrow:"邮箱登录",title:"欢迎使用 FreeAIPPT",lead:"输入邮箱，我们会发送一个安全的 6 位登录验证码。",email:"请输入邮箱",send:"发送验证码",sending:"发送中…",codeTitle:"请查看邮箱",codeLead:"请输入发送至以下邮箱的 6 位验证码：",code:"6 位验证码",verify:"验证并登录",verifying:"验证中…",resend:"更换邮箱",success:"登录成功。",signedIn:"当前登录邮箱",signOut:"退出登录",close:"关闭",error:"操作失败，请稍后重试。"},
  "zh-TW":{...en,signIn:"登入",eyebrow:"電子郵件登入",title:"歡迎使用 FreeAIPPT",lead:"輸入電子郵件，我們會傳送安全的 6 位登入驗證碼。",email:"請輸入電子郵件",send:"傳送驗證碼",sending:"傳送中…",codeTitle:"請查看信箱",codeLead:"請輸入傳送至以下信箱的 6 位驗證碼：",code:"6 位驗證碼",verify:"驗證並登入",verifying:"驗證中…",resend:"更換信箱",success:"登入成功。",signedIn:"目前登入信箱",signOut:"登出",close:"關閉",error:"操作失敗，請稍後再試。"},
  ja:{...en,signIn:"ログイン",eyebrow:"メールでログイン",title:"FreeAIPPTへようこそ",lead:"メールアドレスを入力すると、安全な6桁のコードを送信します。",email:"メールアドレス",send:"コードを送信",sending:"送信中…",codeTitle:"受信トレイを確認",codeLead:"次のメールに届いた6桁のコードを入力してください：",code:"6桁のコード",verify:"確認してログイン",verifying:"確認中…",resend:"別のメールを使う",success:"ログインしました。",signedIn:"ログイン中",signOut:"ログアウト",close:"閉じる",error:"エラーが発生しました。もう一度お試しください。"},
  ko:{...en,signIn:"로그인",eyebrow:"이메일 로그인",title:"FreeAIPPT에 오신 것을 환영합니다",lead:"이메일을 입력하면 안전한 6자리 로그인 코드를 보내드립니다.",email:"이메일 주소",send:"코드 보내기",sending:"전송 중…",codeTitle:"받은편지함을 확인하세요",codeLead:"다음 이메일로 전송된 6자리 코드를 입력하세요:",code:"6자리 코드",verify:"확인하고 로그인",verifying:"확인 중…",resend:"다른 이메일 사용",success:"로그인되었습니다.",signedIn:"로그인 계정",signOut:"로그아웃",close:"닫기",error:"오류가 발생했습니다. 다시 시도해 주세요."},
  fr:{...en,signIn:"Connexion",eyebrow:"CONNEXION PAR E-MAIL",title:"Bienvenue sur FreeAIPPT",lead:"Saisissez votre e-mail pour recevoir un code sécurisé à 6 chiffres.",email:"vous@entreprise.com",send:"Envoyer le code",sending:"Envoi…",codeTitle:"Consultez votre boîte mail",codeLead:"Saisissez le code à 6 chiffres envoyé à",code:"Code à 6 chiffres",verify:"Vérifier et se connecter",verifying:"Vérification…",resend:"Utiliser un autre e-mail",success:"Vous êtes connecté.",signedIn:"Connecté en tant que",signOut:"Se déconnecter",close:"Fermer",error:"Une erreur est survenue. Réessayez."},
  es:{...en,signIn:"Iniciar sesión",eyebrow:"ACCESO POR CORREO",title:"Te damos la bienvenida a FreeAIPPT",lead:"Introduce tu correo y te enviaremos un código seguro de 6 dígitos.",email:"tu@empresa.com",send:"Enviar código",sending:"Enviando…",codeTitle:"Revisa tu bandeja",codeLead:"Introduce el código de 6 dígitos enviado a",code:"Código de 6 dígitos",verify:"Verificar e iniciar sesión",verifying:"Verificando…",resend:"Usar otro correo",success:"Has iniciado sesión.",signedIn:"Sesión iniciada como",signOut:"Cerrar sesión",close:"Cerrar",error:"Ha ocurrido un error. Inténtalo de nuevo."},
  ru:{...en,signIn:"Войти",eyebrow:"ВХОД ПО EMAIL",title:"Добро пожаловать в FreeAIPPT",lead:"Введите email, и мы отправим безопасный шестизначный код.",email:"you@company.com",send:"Отправить код",sending:"Отправка…",codeTitle:"Проверьте почту",codeLead:"Введите шестизначный код, отправленный на",code:"Шестизначный код",verify:"Подтвердить и войти",verifying:"Проверка…",resend:"Другой email",success:"Вы вошли в систему.",signedIn:"Вы вошли как",signOut:"Выйти",close:"Закрыть",error:"Произошла ошибка. Попробуйте ещё раз."},
};

const passwordText: Record<Locale,{ password:string; passwordLogin:string; useCode:string; setPassword:string; changePassword:string; current:string; newPassword:string; save:string; saved:string; rule:string }> = {
  en:{password:"Password",passwordLogin:"Sign in with password",useCode:"Sign in with email code",setPassword:"Set password",changePassword:"Change password",current:"Current password",newPassword:"New password",save:"Save password",saved:"Password updated.",rule:"Use 8–128 characters."},
  "zh-CN":{password:"密码",passwordLogin:"使用密码登录",useCode:"使用邮箱验证码登录",setPassword:"设置密码",changePassword:"修改密码",current:"当前密码",newPassword:"新密码",save:"保存密码",saved:"密码已更新。",rule:"请输入 8–128 个字符。"},
  "zh-TW":{password:"密碼",passwordLogin:"使用密碼登入",useCode:"使用電子郵件驗證碼登入",setPassword:"設定密碼",changePassword:"修改密碼",current:"目前密碼",newPassword:"新密碼",save:"儲存密碼",saved:"密碼已更新。",rule:"請輸入 8–128 個字元。"},
  ja:{password:"パスワード",passwordLogin:"パスワードでログイン",useCode:"メールコードでログイン",setPassword:"パスワードを設定",changePassword:"パスワードを変更",current:"現在のパスワード",newPassword:"新しいパスワード",save:"パスワードを保存",saved:"パスワードを更新しました。",rule:"8～128文字で入力してください。"},
  ko:{password:"비밀번호",passwordLogin:"비밀번호로 로그인",useCode:"이메일 코드로 로그인",setPassword:"비밀번호 설정",changePassword:"비밀번호 변경",current:"현재 비밀번호",newPassword:"새 비밀번호",save:"비밀번호 저장",saved:"비밀번호가 변경되었습니다.",rule:"8~128자로 입력하세요."},
  fr:{password:"Mot de passe",passwordLogin:"Connexion par mot de passe",useCode:"Connexion par code e-mail",setPassword:"Définir un mot de passe",changePassword:"Modifier le mot de passe",current:"Mot de passe actuel",newPassword:"Nouveau mot de passe",save:"Enregistrer",saved:"Mot de passe mis à jour.",rule:"Utilisez entre 8 et 128 caractères."},
  es:{password:"Contraseña",passwordLogin:"Entrar con contraseña",useCode:"Entrar con código de correo",setPassword:"Crear contraseña",changePassword:"Cambiar contraseña",current:"Contraseña actual",newPassword:"Nueva contraseña",save:"Guardar contraseña",saved:"Contraseña actualizada.",rule:"Usa entre 8 y 128 caracteres."},
  ru:{password:"Пароль",passwordLogin:"Войти с паролем",useCode:"Войти по коду из письма",setPassword:"Установить пароль",changePassword:"Изменить пароль",current:"Текущий пароль",newPassword:"Новый пароль",save:"Сохранить пароль",saved:"Пароль обновлён.",rule:"Используйте от 8 до 128 символов."},
};

const signupText: Record<Locale,{ signUp:string; title:string; lead:string; haveAccount:string; needAccount:string }> = {
  en:{signUp:"Sign up",title:"Create your FreeAIPPT account",lead:"Sign up with your email. Your first presentation is free.",haveAccount:"Already have an account? Sign in",needAccount:"New to FreeAIPPT? Sign up"},
  "zh-CN":{signUp:"注册",title:"创建 FreeAIPPT 账号",lead:"使用邮箱注册，首次生成 PPT 免费。",haveAccount:"已有账号？登录",needAccount:"还没有账号？注册"},
  "zh-TW":{signUp:"註冊",title:"建立 FreeAIPPT 帳號",lead:"使用電子郵件註冊，首次生成簡報免費。",haveAccount:"已有帳號？登入",needAccount:"還沒有帳號？註冊"},
  ja:{signUp:"新規登録",title:"FreeAIPPTアカウントを作成",lead:"メールで登録すると、最初のプレゼンテーションは無料です。",haveAccount:"アカウントをお持ちですか？ログイン",needAccount:"初めてですか？新規登録"},
  ko:{signUp:"가입",title:"FreeAIPPT 계정 만들기",lead:"이메일로 가입하면 첫 프레젠테이션이 무료입니다.",haveAccount:"계정이 있나요? 로그인",needAccount:"처음이신가요? 가입"},
  fr:{signUp:"S’inscrire",title:"Créez votre compte FreeAIPPT",lead:"Inscrivez-vous par e-mail. Votre première présentation est gratuite.",haveAccount:"Déjà inscrit ? Se connecter",needAccount:"Nouveau sur FreeAIPPT ? S’inscrire"},
  es:{signUp:"Registrarse",title:"Crea tu cuenta de FreeAIPPT",lead:"Regístrate con tu correo. Tu primera presentación es gratis.",haveAccount:"¿Ya tienes cuenta? Inicia sesión",needAccount:"¿Eres nuevo? Regístrate"},
  ru:{signUp:"Регистрация",title:"Создайте аккаунт FreeAIPPT",lead:"Зарегистрируйтесь по email. Первая презентация бесплатна.",haveAccount:"Уже есть аккаунт? Войти",needAccount:"Впервые в FreeAIPPT? Регистрация"},
};

const menuText: Record<Locale,{ account:string; admin:string }> = {
  en:{account:"Account",admin:"Admin panel"},"zh-CN":{account:"个人账户",admin:"管理员面板"},"zh-TW":{account:"個人帳戶",admin:"管理員面板"},ja:{account:"アカウント",admin:"管理画面"},ko:{account:"계정",admin:"관리자 패널"},fr:{account:"Compte",admin:"Administration"},es:{account:"Cuenta",admin:"Panel de administración"},ru:{account:"Аккаунт",admin:"Панель администратора"},
};

async function api(path: string, body: object, token?: string) {
  const response = await fetch(path, { method:"POST", headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}, body:JSON.stringify(body) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "request failed");
  return data;
}

export function AuthButton({ locale = "en" }: { locale?: Locale }) {
  const t=copy[locale],p=passwordText[locale],s=signupText[locale],m=menuText[locale];
  const [open,setOpen]=useState(false),[step,setStep]=useState<"email"|"code"|"done"|"password">("email"),[passwordMode,setPasswordMode]=useState(false),[signupMode,setSignupMode]=useState(false);
  const [menu,setMenu]=useState(false);
  const [email,setEmail]=useState(""),[code,setCode]=useState(""),[password,setPassword]=useState(""),[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[session,setSession]=useState<Session|null>(null);
  const menuRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const saved=readAuthSession();if(!saved)return;identifyUser(saved.user.id);setSession({...saved,is_admin:false});void fetch("/api/v1/auth/me",{headers:{Authorization:`Bearer ${saved.token}`},cache:"no-store"}).then(async response=>{if(response.status===401){clearAuthSession();setSession(null);return;}if(!response.ok)return;const account=await response.json() as Pick<Session,"user"|"password_set"|"is_admin">;const next={...saved,...account};saveAuthSession(next);setSession(next);}).catch(()=>{});},[]);
  useEffect(()=>{const show=()=>{captureConversion(conversionEvents.authDialogOpened,{locale,signed_in:Boolean(readAuthSession())});setOpen(true);};window.addEventListener(AUTH_OPEN_EVENT,show);return()=>window.removeEventListener(AUTH_OPEN_EVENT,show);},[locale]);
  useEffect(()=>{if(!open){setError("");setCode("");setStep(session?"done":"email");}},[open,session]);
  useEffect(()=>{const close=(event:PointerEvent)=>{if(menuRef.current&&!menuRef.current.contains(event.target as Node))setMenu(false);};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close);},[]);
  const submitEmail=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{if(passwordMode){const next=await api("/api/v1/auth/password-login",{email,password}) as Session;saveAuthSession(next);identifyUser(next.user.id);captureConversion(conversionEvents.signinCompleted,{auth_method:"password",locale});setSession(next);setStep("done");}else{await api(signupMode?"/api/v1/auth/signup/request-code":"/api/v1/auth/request-code",{email});captureConversion(signupMode?conversionEvents.signupCodeRequested:conversionEvents.signinCodeRequested,{locale});setStep("code");}}catch(err){setError(err instanceof Error?err.message:t.error);}finally{setBusy(false);}};
  const submitCode=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const next=await api(signupMode?"/api/v1/auth/signup/verify-code":"/api/v1/auth/verify-code",{email,code}) as Session;saveAuthSession(next);identifyUser(next.user.id);captureConversion(signupMode?conversionEvents.signupCompleted:conversionEvents.signinCompleted,{auth_method:"email_code",locale});setSession(next);setStep("done");}catch(err){setError(err instanceof Error?err.message:t.error);}finally{setBusy(false);}};
  const signOut=()=>{captureConversion(conversionEvents.signoutCompleted,{locale});resetAnalyticsUser();clearAuthSession();setSession(null);setStep("email");setOpen(false);setMenu(false);};
  const savePassword=async(e:FormEvent)=>{e.preventDefault();if(!session)return;setBusy(true);setError("");setNotice("");try{const mode=session.password_set?"change":"set";await api("/api/v1/auth/password",{current_password:session.password_set?currentPassword:null,new_password:newPassword},session.token);const next={...session,password_set:true};saveAuthSession(next);captureConversion(conversionEvents.passwordConfigured,{locale,mode});setSession(next);setCurrentPassword("");setNewPassword("");setNotice(p.saved);setStep("done");}catch(err){setError(err instanceof Error?err.message:t.error);}finally{setBusy(false);}};
  return <div className="account-menu-wrap" ref={menuRef}>
    {!session?<button data-testid="auth-trigger" className="login-button auth-trigger" onClick={()=>{captureConversion(conversionEvents.authDialogOpened,{locale,signed_in:false});setOpen(true);}}>{t.signIn}</button>:<><button data-testid="account-menu-trigger" className="login-button account-menu-trigger" onClick={()=>setMenu(!menu)} title={session.user.email} aria-expanded={menu}><UserRound size={16}/><span>{session.user.email.split("@")[0]}</span><ChevronDown size={14}/></button>{menu&&<div className="account-menu" role="menu"><div className="account-menu-head"><span>{m.account}</span><strong>{session.user.email}</strong></div>{session.is_admin&&<Link data-testid="account-menu-admin" href="/admin" role="menuitem" onClick={()=>setMenu(false)}><LayoutDashboard size={16}/>{m.admin}</Link>}<button data-testid="account-menu-password" role="menuitem" onClick={()=>{setMenu(false);setNotice("");setStep("password");setOpen(true);}}><ShieldCheck size={16}/>{session.password_set?p.changePassword:p.setPassword}</button><button data-testid="account-menu-sign-out" role="menuitem" onClick={signOut}><LogOut size={16}/>{t.signOut}</button></div>}</>}
    {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><section className="modal auth-modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="auth-title"><button data-testid="auth-modal-close" className="modal-close" onClick={()=>setOpen(false)} aria-label={t.close}><X size={18}/></button>
      {step==="email"&&<><span className="eyebrow"><Mail size={14}/> {signupMode?s.signUp:t.eyebrow}</span><h2 id="auth-title">{signupMode?s.title:t.title}</h2><p>{signupMode?s.lead:(passwordMode?p.passwordLogin:t.lead)}</p><form className="auth-form" onSubmit={submitEmail}><label htmlFor="auth-email">Email</label><input id="auth-email" autoFocus autoComplete="email" type="email" required value={email} placeholder={t.email} onChange={e=>setEmail(e.target.value)}/>{passwordMode&&<><label htmlFor="auth-password">{p.password}</label><input id="auth-password" autoComplete="current-password" type="password" minLength={8} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></>}<button data-testid="auth-email-submit" className="primary-button" disabled={busy}>{busy?t.sending:(passwordMode?t.signIn:t.send)}</button>{!signupMode&&<button data-testid="auth-password-mode-toggle" type="button" className="auth-link" onClick={()=>{setPasswordMode(!passwordMode);setError("");}}>{passwordMode?p.useCode:p.passwordLogin}</button>}<button data-testid="auth-signup-mode-toggle" type="button" className="auth-link auth-mode-link" onClick={()=>{if(!signupMode)captureConversion(conversionEvents.signupStarted,{entry_point:"header_auth",locale});setSignupMode(!signupMode);setPasswordMode(false);setPassword("");setError("");}}>{signupMode?s.haveAccount:s.needAccount}</button></form></>}
      {step==="code"&&<><span className="eyebrow"><ShieldCheck size={14}/> {t.eyebrow}</span><h2 id="auth-title">{t.codeTitle}</h2><p>{t.codeLead}<br/><strong>{email}</strong></p><form className="auth-form" onSubmit={submitCode}><label htmlFor="auth-code">{t.code}</label><input id="auth-code" className="code-input" autoFocus autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={code} placeholder="000000" onChange={e=>setCode(e.target.value.replace(/\D/g,""))}/><button data-testid="auth-code-submit" className="primary-button" disabled={busy||code.length!==6}>{busy?t.verifying:t.verify}</button><button data-testid="auth-email-change" type="button" className="auth-link" onClick={()=>{setStep("email");setCode("");setError("");}}>{t.resend}</button></form></>}
      {step==="password"&&session&&<><span className="eyebrow"><ShieldCheck size={14}/> {session.password_set?p.changePassword:p.setPassword}</span><h2 id="auth-title">{session.password_set?p.changePassword:p.setPassword}</h2><p>{p.rule}</p><form className="auth-form" onSubmit={savePassword}>{session.password_set&&<><label htmlFor="current-password">{p.current}</label><input id="current-password" autoFocus autoComplete="current-password" type="password" minLength={8} maxLength={128} required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></>}<label htmlFor="new-password">{p.newPassword}</label><input id="new-password" autoFocus={!session.password_set} autoComplete="new-password" type="password" minLength={8} maxLength={128} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><button data-testid="auth-password-save" className="primary-button" disabled={busy}>{busy?t.verifying:p.save}</button><button data-testid="auth-password-cancel" type="button" className="auth-link" onClick={()=>{setStep("done");setError("");}}>{t.close}</button></form></>}
      {step==="done"&&session&&<div className="auth-account"><CheckCircle2/><h2 id="auth-title">{notice||t.success}</h2><p>{t.signedIn}<br/><strong>{session.user.email}</strong></p><button data-testid="auth-success-close" className="primary-button" onClick={()=>setOpen(false)}>{t.close}</button></div>}
      {error&&<p className="auth-error" role="alert">{error}</p>}
    </section></div>}
  </div>;
}
