export const locales = ["en", "zh-CN", "zh-TW", "ja", "ko", "fr", "es", "ru"] as const;
export type Locale = (typeof locales)[number];

export const localeNames: Record<Locale, string> = {
  en: "English",
  "zh-CN": "简体中文",
  "zh-TW": "繁體中文",
  ja: "日本語",
  ko: "한국어",
  fr: "Français",
  es: "Español",
  ru: "Русский",
};

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

export function localizePath(locale: Locale, path = "") {
  const clean = path === "/" ? "" : path.startsWith("/") ? path : `/${path}`;
  return locale === "en" ? clean || "/" : `/${locale}${clean}`;
}

export function languageAlternates(path = "") {
  return Object.fromEntries(locales.map((locale) => [locale, localizePath(locale, path)]));
}

export type Translation = {
  meta: { title: string; description: string };
  nav: { resources: string; decks: string; pricing: string; signIn: string; language: string };
  home: {
    badge: string; title1: string; title2: string; lead: string;
    trust: string[]; eyebrow: string; stepsTitle: string;
    steps: Array<{ title: string; text: string }>;
  };
  generator: { placeholder: string; label: string; attach: string; drop: string; limit: string; remove: string };
  modal: { close: string; eyebrow: string; title: string; text: string; email: string; button: string; success: string };
  pricing: {
    badge: string; title1: string; title2: string; lead: string; popular: string; note: string;
    benefits: string[];
    plans: Array<{ name: string; price: string; unit: string; detail: string; credits: string; button: string }>;
  };
  queue: {
    eyebrow: string; title: string; lead: string; newDeck: string; generating: string; ready: string;
    item1: string; item1Meta: string; item2: string; item2Meta: string; demo: string; demoText: string;
  };
  resources: {
    eyebrow: string; title1: string; title2: string; lead: string; latest: string; section: string;
    type: string; articleTitle: string; articleText: string;
  };
  article: {
    home: string; resources: string; crumb: string; kicker: string; title1: string; title2: string;
    lead: string; read: string; updated: string; short: string; shortText: string;
    reference: string; referenceText: string; format: string; ratio: string; size: string; use: string;
    rows: string[][]; pixels: string; pixelsText: string; choose: string; chooseText: string;
    change: string; changeText: string; faqTitle: string; faq: Array<{ q: string; a: string }>;
    ctaBadge: string; ctaTitle: string; ctaText: string; ctaButton: string;
  };
};

const en: Translation = {
  meta: { title: "FreePPT — AI presentations from anything", description: "Turn a prompt or document into a polished presentation. Try your first deck free." },
  nav: { resources: "Resources", decks: "My decks", pricing: "Pricing", signIn: "Sign in", language: "Language" },
  home: { badge: "YOUR FIRST DECK IS FREE", title1: "From rough idea to", title2: "ready-to-present.", lead: "Tell us what you need or upload what you have. FreePPT turns it into a clear, polished presentation—in minutes.", trust: ["No credit card", "Editable PPTX", "Shareable HTML"], eyebrow: "THE SIMPLEST WAY TO MAKE A DECK", stepsTitle: "Bring the idea. We'll build the slides.", steps: [{ title: "Give us the context", text: "Type a brief or attach your Word, PowerPoint, Excel, PDF, and image files." }, { title: "Join the queue", text: "Our AI structures your story, writes the content, and designs every slide." }, { title: "Download both formats", text: "Get an editable PPTX and a responsive HTML presentation—ready to use." }] },
  generator: { placeholder: "Describe the presentation you want to create…", label: "Presentation brief", attach: "Attach files", drop: "or drop them here", limit: "Up to 25 MB", remove: "Remove" },
  modal: { close: "Close", eyebrow: "EARLY ACCESS", title: "Generation is coming soon.", text: "We're polishing the deck engine. Join the list and get your first presentation free when we launch.", email: "you@company.com", button: "Notify me", success: "You're on the list. We'll be in touch!" },
  pricing: { badge: "SIMPLE, CREDIT-BASED PRICING", title1: "One great deck.", title2: "One clear price.", lead: "No subscriptions. Start free, then buy presentation credits whenever you need them.", popular: "MOST POPULAR", note: "Every generation includes both PPTX and HTML formats. Payments are coming soon.", benefits: ["Editable PPTX download", "Shareable HTML version", "Files up to 25 MB"], plans: [{ name: "First deck", price: "$0", unit: "one time", detail: "Create one complete presentation after signing up.", credits: "1 deck", button: "Start for free" }, { name: "Single deck", price: "$5", unit: "per deck", detail: "Pay only when you need another polished presentation.", credits: "1 deck", button: "Create a deck" }, { name: "10-deck pack", price: "$40", unit: "$4 / deck", detail: "For regular presenters. Credits never expire.", credits: "10 decks · Save 20%", button: "Buy 10 decks" }, { name: "25-deck pack", price: "$75", unit: "$3 / deck", detail: "For teams and high-volume presentation work.", credits: "25 decks · Save 40%", button: "Buy 25 decks" }] },
  queue: { eyebrow: "MY DECKS", title: "Your presentation queue", lead: "Track generations and download completed decks in both formats.", newDeck: "New deck", generating: "GENERATING", ready: "READY", item1: "Quarterly product strategy", item1Meta: "Generating · Added just now", item2: "Remote work trends 2026", item2Meta: "12 slides · Completed yesterday", demo: "DEMO QUEUE", demoText: "Generation history and downloads will become available at launch." },
  resources: { eyebrow: "FREEPPT RESOURCES", title1: "Make every presentation", title2: "clearer and stronger.", lead: "Practical answers, tested workflows, and straightforward guides for better slides.", latest: "Latest guide", section: "Presentation essentials", type: "POWERPOINT BASICS · 8 MIN READ", articleTitle: "PowerPoint Slide Size: Dimensions, Pixels, and How to Change It", articleText: "Find the right dimensions for widescreen, standard, posters, social media, and printed presentations." },
  article: { home: "Home", resources: "Resources", crumb: "PowerPoint slide size", kicker: "POWERPOINT BASICS", title1: "PowerPoint slide size:", title2: "dimensions, pixels, and formats", lead: "The standard PowerPoint slide size is 13.333 × 7.5 inches for a 16:9 widescreen presentation.", read: "8 min read", updated: "Updated September 4, 2026", short: "The short answer", shortText: "Choose Widescreen (16:9) for almost every new presentation. Use 4:3 only for older equipment and custom sizes for print or specific platforms.", reference: "PowerPoint slide size quick reference", referenceText: "PowerPoint stores slide size in inches or centimeters, not pixels.", format: "Format", ratio: "Aspect ratio", size: "Size", use: "Common use", rows: [["Widescreen", "16:9", "13.333 × 7.5 in", "Modern screens and video calls"], ["Standard", "4:3", "10 × 7.5 in", "Older projectors"], ["A4", "1.41:1", "29.7 × 21 cm", "Print layouts"]], pixels: "PowerPoint slide size in pixels", pixelsText: "Slides do not have one fixed pixel size. A 16:9 slide is commonly exported at 1280 × 720 (HD) or 1920 × 1080 (Full HD).", choose: "Should you choose 16:9 or 4:3?", chooseText: "Use 16:9 unless a venue, projector, or existing template specifically requires 4:3. It fits modern displays and online meetings.", change: "How to change slide size", changeText: "In PowerPoint, open Design → Slide Size. Choose a preset or Custom Slide Size, select Ensure Fit, then inspect every layout.", faqTitle: "Frequently asked questions", faq: [{ q: "What is the standard PowerPoint slide size?", a: "The modern default is Widescreen (16:9), measuring 13.333 × 7.5 inches." }, { q: "Can I resize an existing deck?", a: "Yes. Save a copy first, choose Ensure Fit, and inspect text, images, and charts afterward." }], ctaBadge: "FIRST DECK FREE", ctaTitle: "Start with the right format.", ctaText: "Describe your presentation or upload a document. Get editable PPTX and shareable HTML formats.", ctaButton: "Create your presentation" },
};

const zhCN: Translation = {
  ...en,
  meta: { title: "FreePPT｜免费 AI PPT 生成器", description: "输入需求或上传文档，AI 快速生成专业演示文稿。注册后免费试用一次。" },
  nav: { resources: "资源", decks: "我的演示", pricing: "价格", signIn: "登录", language: "语言" },
  home: { badge: "首份演示文稿免费", title1: "从一个想法到", title2: "随时可以演示。", lead: "输入你的需求，或上传已有材料。FreePPT 可在几分钟内生成清晰、专业的演示文稿。", trust: ["无需信用卡", "可编辑 PPTX", "可分享 HTML"], eyebrow: "制作演示文稿，就这么简单", stepsTitle: "你提供想法，我们完成幻灯片。", steps: [{ title: "提供背景材料", text: "输入简单说明，或上传 Word、PowerPoint、Excel、PDF 和图片。" }, { title: "进入生成队列", text: "AI 自动梳理逻辑、撰写内容并设计每一页。" }, { title: "下载两种格式", text: "获得可编辑 PPTX 和响应式 HTML 演示文稿。" }] },
  generator: { placeholder: "描述你想制作的演示文稿……", label: "演示文稿需求", attach: "上传附件", drop: "或拖放到此处", limit: "最大 25 MB", remove: "移除" },
  modal: { close: "关闭", eyebrow: "抢先体验", title: "生成功能即将上线", text: "我们正在完善生成引擎。加入候补名单，上线后即可免费制作第一份演示文稿。", email: "你的邮箱", button: "通知我", success: "登记成功，上线后我们会通知你！" },
  pricing: { badge: "简单的次数定价", title1: "一份好演示，", title2: "一个清晰价格。", lead: "无需订阅。首次免费，之后按需购买生成次数。", popular: "最受欢迎", note: "每次生成均包含 PPTX 和 HTML 两种格式，支付功能即将上线。", benefits: ["可编辑 PPTX 下载", "可分享 HTML 版本", "支持最大 25 MB 文件"], plans: [{ name: "首次体验", price: "$0", unit: "仅一次", detail: "注册后免费生成一份完整演示文稿。", credits: "1 次", button: "免费开始" }, { name: "单次生成", price: "$5", unit: "每次", detail: "需要时再付费，不必订阅。", credits: "1 次", button: "制作演示" }, { name: "10 次套餐", price: "$40", unit: "$4 / 次", detail: "适合经常制作演示的人，次数永不过期。", credits: "10 次 · 节省 20%", button: "购买 10 次" }, { name: "25 次套餐", price: "$75", unit: "$3 / 次", detail: "适合团队和高频演示需求。", credits: "25 次 · 节省 40%", button: "购买 25 次" }] },
  queue: { eyebrow: "我的演示", title: "演示文稿生成队列", lead: "查看生成进度，并下载两种格式的成品。", newDeck: "新建演示", generating: "生成中", ready: "已完成", item1: "季度产品策略", item1Meta: "正在生成 · 刚刚添加", item2: "2026 远程办公趋势", item2Meta: "12 页 · 昨日完成", demo: "演示队列", demoText: "生成历史和下载功能将在正式上线后开放。" },
  resources: { eyebrow: "FREEPPT 资源", title1: "让每一份演示", title2: "更清晰、更有力。", lead: "实用答案、经过验证的流程，以及简单直接的幻灯片指南。", latest: "最新指南", section: "演示文稿基础", type: "POWERPOINT 基础 · 阅读 8 分钟", articleTitle: "PowerPoint 幻灯片尺寸：比例、像素与修改方法", articleText: "了解宽屏、标准、海报、社交媒体和打印演示的正确尺寸。" },
  article: { home: "首页", resources: "资源", crumb: "PowerPoint 幻灯片尺寸", kicker: "POWERPOINT 基础", title1: "PowerPoint 幻灯片尺寸：", title2: "比例、像素与格式", lead: "16:9 宽屏演示的标准 PowerPoint 尺寸为 13.333 × 7.5 英寸。", read: "阅读 8 分钟", updated: "更新于 2026 年 9 月 4 日", short: "简短答案", shortText: "几乎所有新演示都应选择宽屏（16:9）。只有旧设备使用 4:3，打印或特定平台使用自定义尺寸。", reference: "PowerPoint 尺寸速查", referenceText: "PowerPoint 使用英寸或厘米保存尺寸，而不是固定像素。", format: "格式", ratio: "宽高比", size: "尺寸", use: "常见用途", rows: [["宽屏", "16:9", "13.333 × 7.5 英寸", "现代屏幕与视频会议"], ["标准", "4:3", "10 × 7.5 英寸", "旧式投影仪"], ["A4", "1.41:1", "29.7 × 21 厘米", "打印版式"]], pixels: "PowerPoint 幻灯片像素尺寸", pixelsText: "幻灯片没有唯一固定像素。16:9 通常导出为 1280 × 720（HD）或 1920 × 1080（全高清）。", choose: "应该选择 16:9 还是 4:3？", chooseText: "除非场地、投影仪或现有模板明确要求 4:3，否则选择 16:9。它更适合现代显示器和线上会议。", change: "如何修改幻灯片尺寸", changeText: "在 PowerPoint 中打开“设计 → 幻灯片大小”，选择预设或自定义尺寸，使用“确保适合”，再检查所有版式。", faqTitle: "常见问题", faq: [{ q: "标准 PowerPoint 幻灯片尺寸是多少？", a: "当前默认是 16:9 宽屏，尺寸为 13.333 × 7.5 英寸。" }, { q: "可以调整已有演示文稿的尺寸吗？", a: "可以。先保存副本，选择“确保适合”，然后检查文字、图片和图表。" }], ctaBadge: "首份免费", ctaTitle: "从正确的格式开始。", ctaText: "描述需求或上传文档，即可获得可编辑 PPTX 和可分享 HTML。", ctaButton: "制作演示文稿" },
};

const zhTW: Translation = {
  ...zhCN,
  meta: { title: "FreePPT｜免費 AI 簡報產生器", description: "輸入需求或上傳文件，由 AI 快速產生專業簡報。註冊後可免費試用一次。" },
  nav: { resources: "資源", decks: "我的簡報", pricing: "價格", signIn: "登入", language: "語言" },
  home: { badge: "首份簡報免費", title1: "從一個想法到", title2: "隨時可以上台。", lead: "輸入需求，或上傳現有資料。FreePPT 幾分鐘內就能產生清楚、專業的簡報。", trust: ["無需信用卡", "可編輯 PPTX", "可分享 HTML"], eyebrow: "製作簡報，就是這麼簡單", stepsTitle: "你提供想法，我們完成投影片。", steps: [{ title: "提供背景資料", text: "輸入簡短說明，或上傳 Word、PowerPoint、Excel、PDF 與圖片。" }, { title: "進入產生佇列", text: "AI 自動整理邏輯、撰寫內容並設計每張投影片。" }, { title: "下載兩種格式", text: "取得可編輯 PPTX 與響應式 HTML 簡報。" }] },
  generator: { placeholder: "描述你想製作的簡報……", label: "簡報需求", attach: "上傳附件", drop: "或拖放至此", limit: "最大 25 MB", remove: "移除" },
  modal: { close: "關閉", eyebrow: "搶先體驗", title: "產生功能即將上線", text: "我們正在完善簡報引擎。加入等候名單，上線後即可免費製作第一份簡報。", email: "你的電子郵件", button: "通知我", success: "登記成功，上線後我們會通知你！" },
  pricing: { ...zhCN.pricing, badge: "簡單的次數定價", title1: "一份好簡報，", title2: "一個清楚價格。", lead: "無需訂閱。首次免費，之後按需購買產生次數。", popular: "最受歡迎", note: "每次產生均包含 PPTX 與 HTML，付款功能即將上線。", benefits: ["可編輯 PPTX 下載", "可分享 HTML 版本", "支援最大 25 MB 檔案"], plans: [{ name: "首次體驗", price: "$0", unit: "僅一次", detail: "註冊後免費產生一份完整簡報。", credits: "1 次", button: "免費開始" }, { name: "單次產生", price: "$5", unit: "每次", detail: "需要時再付費，不必訂閱。", credits: "1 次", button: "製作簡報" }, { name: "10 次方案", price: "$40", unit: "$4 / 次", detail: "適合經常製作簡報的人，次數永不過期。", credits: "10 次 · 節省 20%", button: "購買 10 次" }, { name: "25 次方案", price: "$75", unit: "$3 / 次", detail: "適合團隊和高頻簡報需求。", credits: "25 次 · 節省 40%", button: "購買 25 次" }] },
  queue: { ...zhCN.queue, eyebrow: "我的簡報", title: "簡報產生佇列", lead: "查看產生進度，並下載兩種格式的成品。", newDeck: "新增簡報", generating: "產生中", ready: "已完成", item1Meta: "正在產生 · 剛剛加入", item2Meta: "12 頁 · 昨日完成", demo: "示範佇列", demoText: "產生記錄與下載功能將於正式上線後開放。" },
  resources: { ...zhCN.resources, title1: "讓每一份簡報", title2: "更清楚、更有力。", lead: "實用答案、經過驗證的流程，以及簡單直接的投影片指南。", articleTitle: "PowerPoint 投影片尺寸：比例、像素與修改方法", articleText: "了解寬螢幕、標準、海報、社群媒體和列印簡報的正確尺寸。" },
  article: { ...zhCN.article, home: "首頁", resources: "資源", crumb: "PowerPoint 投影片尺寸", title1: "PowerPoint 投影片尺寸：", title2: "比例、像素與格式", short: "簡短答案", faqTitle: "常見問題", ctaBadge: "首份免費", ctaButton: "製作簡報" },
};

function translated(base: Translation, value: Partial<Translation>): Translation { return { ...base, ...value } as Translation; }

const ja = translated(en, {
  meta: { title: "FreePPT｜無料AIプレゼン作成ツール", description: "指示を入力または資料をアップロードして、AIで美しいプレゼンを作成。初回は無料です。" },
  nav: { resources: "資料", decks: "マイ資料", pricing: "料金", signIn: "ログイン", language: "言語" },
  home: { badge: "最初の1本は無料", title1: "アイデアから", title2: "発表できる資料へ。", lead: "要望を入力するか資料をアップロード。FreePPTが数分で明快なプレゼンに仕上げます。", trust: ["カード登録不要", "編集可能なPPTX", "共有可能なHTML"], eyebrow: "いちばん簡単なスライド作成", stepsTitle: "アイデアをください。スライドはお任せください。", steps: [{ title: "内容を伝える", text: "概要を入力、またはWord、PowerPoint、Excel、PDF、画像を添付します。" }, { title: "生成キューへ", text: "AIが構成、文章、各スライドのデザインを作成します。" }, { title: "2形式でダウンロード", text: "編集可能なPPTXとレスポンシブHTMLを取得できます。" }] },
  generator: { placeholder: "作りたいプレゼンの内容を入力…", label: "プレゼンの概要", attach: "ファイルを添付", drop: "またはここにドロップ", limit: "最大25 MB", remove: "削除" },
  modal: { close: "閉じる", eyebrow: "先行アクセス", title: "生成機能は近日公開です", text: "現在エンジンを仕上げています。登録すると公開時に最初のプレゼンを無料で作成できます。", email: "メールアドレス", button: "通知を受け取る", success: "登録しました。公開時にお知らせします！" },
  pricing: { ...en.pricing, badge: "シンプルなクレジット料金", title1: "優れた資料を、", title2: "明快な価格で。", lead: "サブスクリプション不要。初回無料、その後は必要な分だけ購入できます。", popular: "人気", note: "すべての生成にPPTXとHTMLが含まれます。決済機能は近日公開です。", benefits: ["編集可能なPPTX", "共有できるHTML", "最大25 MBのファイル"], plans: [{ name: "初回", price: "$0", unit: "1回限り", detail: "登録後、完全なプレゼンを1本無料で作成。", credits: "1本", button: "無料で始める" }, { name: "1本", price: "$5", unit: "1本ごと", detail: "必要なときだけ支払えます。", credits: "1本", button: "作成する" }, { name: "10本パック", price: "$40", unit: "$4 / 本", detail: "定期的に作成する方向け。", credits: "10本 · 20%お得", button: "10本購入" }, { name: "25本パック", price: "$75", unit: "$3 / 本", detail: "チームや大量作成向け。", credits: "25本 · 40%お得", button: "25本購入" }] },
  queue: { ...en.queue, eyebrow: "マイ資料", title: "プレゼン生成キュー", lead: "進行状況を確認し、完成資料を2形式でダウンロードできます。", newDeck: "新規作成", generating: "生成中", ready: "完了", item1: "四半期製品戦略", item1Meta: "生成中 · たった今追加", item2: "2026年リモートワーク動向", item2Meta: "12枚 · 昨日完了", demo: "デモキュー", demoText: "履歴とダウンロードは公開時に利用できます。" },
  resources: { ...en.resources, eyebrow: "FREEPPT 資料", title1: "すべてのプレゼンを", title2: "より明快に、力強く。", lead: "より良いスライドのための実用的な回答とガイド。", latest: "最新ガイド", section: "プレゼンの基本", type: "POWERPOINT 基礎 · 8分", articleTitle: "PowerPointスライドサイズ：寸法・ピクセル・変更方法", articleText: "ワイド、標準、印刷、SNSに適したサイズを確認できます。" },
  article: { ...en.article, home: "ホーム", resources: "資料", crumb: "PowerPointスライドサイズ", kicker: "POWERPOINT 基礎", title1: "PowerPointスライドサイズ：", title2: "寸法・ピクセル・形式", lead: "16:9ワイド画面の標準サイズは13.333 × 7.5インチです。", read: "8分", updated: "2026年9月4日更新", short: "結論", shortText: "ほぼすべての新規資料では16:9を選びます。4:3は古い機器、カスタムサイズは印刷などに使用します。", reference: "スライドサイズ早見表", referenceText: "PowerPointはピクセルではなくインチまたはセンチでサイズを保存します。", format: "形式", ratio: "比率", size: "サイズ", use: "用途", pixels: "ピクセルでのスライドサイズ", pixelsText: "固定ピクセルはありません。16:9は通常1280 × 720または1920 × 1080で書き出します。", choose: "16:9と4:3のどちらを選ぶ？", chooseText: "会場やテンプレートが4:3を指定しない限り、現代の画面に適した16:9を選びます。", change: "スライドサイズの変更方法", changeText: "デザイン → スライドのサイズを開き、サイズを選んで「サイズに合わせて調整」を使用します。", faqTitle: "よくある質問", ctaBadge: "最初の1本は無料", ctaTitle: "適切な形式から始めましょう。", ctaText: "要望を入力または資料をアップロードし、PPTXとHTMLを取得できます。", ctaButton: "プレゼンを作成" },
});

const ko = translated(en, {
  meta: { title: "FreePPT | 무료 AI 프레젠테이션 생성기", description: "요구사항을 입력하거나 문서를 업로드해 AI 프레젠테이션을 만드세요. 첫 1회는 무료입니다." }, nav: { resources: "자료", decks: "내 프레젠테이션", pricing: "요금", signIn: "로그인", language: "언어" },
  home: { badge: "첫 프레젠테이션 무료", title1: "아이디어에서", title2: "발표 가능한 자료까지.", lead: "필요한 내용을 입력하거나 파일을 업로드하세요. FreePPT가 몇 분 만에 깔끔한 프레젠테이션으로 만듭니다.", trust: ["카드 불필요", "편집 가능한 PPTX", "공유 가능한 HTML"], eyebrow: "가장 간단한 슬라이드 제작", stepsTitle: "아이디어만 주세요. 슬라이드는 저희가 만듭니다.", steps: [{ title: "내용 제공", text: "설명을 입력하거나 Word, PowerPoint, Excel, PDF 및 이미지를 첨부하세요." }, { title: "생성 대기열", text: "AI가 스토리를 구성하고 내용을 작성하며 모든 슬라이드를 디자인합니다." }, { title: "두 형식 다운로드", text: "편집 가능한 PPTX와 반응형 HTML을 받으세요." }] },
  generator: { placeholder: "만들고 싶은 프레젠테이션을 설명하세요…", label: "프레젠테이션 설명", attach: "파일 첨부", drop: "또는 여기에 놓기", limit: "최대 25 MB", remove: "삭제" }, modal: { close: "닫기", eyebrow: "얼리 액세스", title: "생성 기능이 곧 출시됩니다", text: "엔진을 다듬고 있습니다. 대기 명단에 등록하면 출시 후 첫 프레젠테이션을 무료로 만들 수 있습니다.", email: "이메일", button: "알림 받기", success: "등록되었습니다. 곧 연락드리겠습니다!" },
  pricing: { ...en.pricing, badge: "간단한 크레딧 요금", title1: "훌륭한 프레젠테이션,", title2: "명확한 가격.", lead: "구독 없이 첫 1회 무료, 이후 필요한 만큼 구매하세요.", popular: "인기", note: "PPTX와 HTML이 모두 포함됩니다. 결제는 곧 출시됩니다.", benefits: ["편집 가능한 PPTX", "공유 가능한 HTML", "최대 25 MB 파일"], plans: [{ name: "첫 1회", price: "$0", unit: "1회", detail: "가입 후 완성된 프레젠테이션 1개를 무료로 만드세요.", credits: "1회", button: "무료 시작" }, { name: "단건", price: "$5", unit: "1회당", detail: "필요할 때만 결제하세요.", credits: "1회", button: "만들기" }, { name: "10회 팩", price: "$40", unit: "$4 / 회", detail: "정기적으로 만드는 사용자를 위한 상품입니다.", credits: "10회 · 20% 절약", button: "10회 구매" }, { name: "25회 팩", price: "$75", unit: "$3 / 회", detail: "팀과 대량 제작을 위한 상품입니다.", credits: "25회 · 40% 절약", button: "25회 구매" }] },
  queue: { ...en.queue, eyebrow: "내 프레젠테이션", title: "프레젠테이션 생성 대기열", lead: "생성 상태를 확인하고 두 형식으로 다운로드하세요.", newDeck: "새로 만들기", generating: "생성 중", ready: "완료", item1: "분기 제품 전략", item1Meta: "생성 중 · 방금 추가", item2: "2026 원격 근무 동향", item2Meta: "12장 · 어제 완료", demo: "데모 대기열", demoText: "기록과 다운로드는 출시 후 제공됩니다." },
  resources: { ...en.resources, eyebrow: "FREEPPT 자료", title1: "모든 프레젠테이션을", title2: "더 명확하고 강하게.", lead: "더 나은 슬라이드를 위한 실용적인 답변과 가이드.", latest: "최신 가이드", section: "프레젠테이션 기본", type: "POWERPOINT 기초 · 8분", articleTitle: "PowerPoint 슬라이드 크기: 치수, 픽셀 및 변경 방법", articleText: "화면, 인쇄 및 소셜 미디어에 맞는 크기를 알아보세요." },
  article: { ...en.article, home: "홈", resources: "자료", crumb: "PowerPoint 슬라이드 크기", kicker: "POWERPOINT 기초", title1: "PowerPoint 슬라이드 크기:", title2: "치수, 픽셀 및 형식", lead: "16:9 와이드스크린 표준 크기는 13.333 × 7.5인치입니다.", read: "8분", updated: "2026년 9월 4일 업데이트", short: "짧은 답", shortText: "대부분의 새 프레젠테이션에는 16:9를 사용하세요. 4:3은 오래된 장비에만 적합합니다.", reference: "슬라이드 크기 빠른 참조", referenceText: "PowerPoint는 픽셀이 아닌 인치 또는 센티미터로 크기를 저장합니다.", format: "형식", ratio: "화면비", size: "크기", use: "용도", pixels: "픽셀 단위 슬라이드 크기", pixelsText: "고정 픽셀은 없습니다. 16:9는 일반적으로 1280 × 720 또는 1920 × 1080으로 내보냅니다.", choose: "16:9 또는 4:3?", chooseText: "장소나 템플릿에서 4:3을 요구하지 않는 한 현대 화면에 맞는 16:9를 사용하세요.", change: "슬라이드 크기 변경", changeText: "디자인 → 슬라이드 크기를 열고 사전 설정 또는 사용자 지정을 선택한 후 맞춤 확인을 사용하세요.", faqTitle: "자주 묻는 질문", ctaBadge: "첫 1회 무료", ctaTitle: "올바른 형식으로 시작하세요.", ctaText: "요구사항 또는 문서를 제공하고 PPTX와 HTML을 받으세요.", ctaButton: "프레젠테이션 만들기" },
});

const fr = translated(en, {
  meta: { title: "FreePPT — Générateur de présentations IA gratuit", description: "Transformez une consigne ou un document en présentation professionnelle. Premier essai gratuit." }, nav: { resources: "Ressources", decks: "Mes présentations", pricing: "Tarifs", signIn: "Connexion", language: "Langue" },
  home: { badge: "VOTRE PREMIÈRE PRÉSENTATION EST GRATUITE", title1: "De l'idée brute à une", title2: "présentation prête.", lead: "Décrivez votre besoin ou importez vos fichiers. FreePPT crée une présentation claire et soignée en quelques minutes.", trust: ["Sans carte bancaire", "PPTX modifiable", "HTML partageable"], eyebrow: "LA FAÇON LA PLUS SIMPLE DE CRÉER", stepsTitle: "Apportez l'idée. Nous créons les diapositives.", steps: [{ title: "Donnez le contexte", text: "Saisissez un brief ou joignez vos fichiers Word, PowerPoint, Excel, PDF et images." }, { title: "Rejoignez la file", text: "L'IA structure le récit, rédige le contenu et conçoit chaque diapositive." }, { title: "Téléchargez les deux formats", text: "Obtenez un PPTX modifiable et une présentation HTML responsive." }] },
  generator: { placeholder: "Décrivez la présentation à créer…", label: "Brief de présentation", attach: "Joindre des fichiers", drop: "ou déposez-les ici", limit: "Jusqu'à 25 Mo", remove: "Supprimer" }, modal: { close: "Fermer", eyebrow: "ACCÈS ANTICIPÉ", title: "La génération arrive bientôt.", text: "Nous finalisons le moteur. Inscrivez-vous et créez gratuitement votre première présentation au lancement.", email: "vous@entreprise.com", button: "Me prévenir", success: "Vous êtes inscrit. À très bientôt !" },
  pricing: { ...en.pricing, badge: "TARIFS SIMPLES PAR CRÉDIT", title1: "Une excellente présentation.", title2: "Un prix clair.", lead: "Sans abonnement. Commencez gratuitement puis achetez des crédits selon vos besoins.", popular: "POPULAIRE", note: "Chaque génération inclut les formats PPTX et HTML. Le paiement arrive bientôt.", benefits: ["PPTX modifiable", "Version HTML partageable", "Fichiers jusqu'à 25 Mo"], plans: [{ name: "Première présentation", price: "$0", unit: "une fois", detail: "Créez une présentation complète après inscription.", credits: "1 présentation", button: "Essayer gratuitement" }, { name: "À l'unité", price: "$5", unit: "par présentation", detail: "Payez uniquement lorsque vous en avez besoin.", credits: "1 présentation", button: "Créer" }, { name: "Pack de 10", price: "$40", unit: "$4 / présentation", detail: "Pour les utilisateurs réguliers.", credits: "10 · Économisez 20 %", button: "Acheter 10" }, { name: "Pack de 25", price: "$75", unit: "$3 / présentation", detail: "Pour les équipes et gros volumes.", credits: "25 · Économisez 40 %", button: "Acheter 25" }] },
  queue: { ...en.queue, eyebrow: "MES PRÉSENTATIONS", title: "File de génération", lead: "Suivez la génération et téléchargez les deux formats.", newDeck: "Nouvelle présentation", generating: "EN COURS", ready: "PRÊTE", item1: "Stratégie produit trimestrielle", item1Meta: "En cours · Ajoutée à l'instant", item2: "Tendances du travail à distance 2026", item2Meta: "12 diapositives · Terminée hier", demo: "FILE DE DÉMO", demoText: "L'historique et les téléchargements seront disponibles au lancement." },
  resources: { ...en.resources, title1: "Rendez chaque présentation", title2: "plus claire et convaincante.", lead: "Réponses pratiques, méthodes testées et guides simples pour de meilleures diapositives.", latest: "Dernier guide", section: "Les essentiels", type: "BASES POWERPOINT · 8 MIN", articleTitle: "Taille des diapositives PowerPoint : dimensions, pixels et modification", articleText: "Choisissez les bonnes dimensions pour écrans, impression et réseaux sociaux." },
  article: { ...en.article, home: "Accueil", resources: "Ressources", crumb: "Taille des diapositives", kicker: "BASES POWERPOINT", title1: "Taille des diapositives :", title2: "dimensions, pixels et formats", lead: "La taille standard 16:9 est de 13,333 × 7,5 pouces.", read: "8 min", updated: "Mis à jour le 4 septembre 2026", short: "En bref", shortText: "Choisissez le format 16:9 pour presque toute nouvelle présentation. Réservez le 4:3 aux anciens équipements.", reference: "Tableau des tailles PowerPoint", referenceText: "PowerPoint stocke les dimensions en pouces ou centimètres, pas en pixels.", format: "Format", ratio: "Ratio", size: "Taille", use: "Usage", pixels: "Taille en pixels", pixelsText: "Il n'existe pas de taille fixe. Le 16:9 s'exporte souvent en 1280 × 720 ou 1920 × 1080.", choose: "Faut-il choisir 16:9 ou 4:3 ?", chooseText: "Utilisez 16:9 sauf si le lieu ou le modèle impose le 4:3. Il convient aux écrans modernes.", change: "Modifier la taille", changeText: "Dans PowerPoint, ouvrez Création → Taille des diapositives, choisissez une taille puis vérifiez chaque mise en page.", faqTitle: "Questions fréquentes", ctaBadge: "PREMIÈRE PRÉSENTATION GRATUITE", ctaTitle: "Commencez avec le bon format.", ctaText: "Décrivez votre besoin ou importez un document pour obtenir les formats PPTX et HTML.", ctaButton: "Créer une présentation" },
});

const es = translated(en, {
  meta: { title: "FreePPT — Generador de presentaciones con IA gratis", description: "Convierte una idea o documento en una presentación profesional. Prueba gratis una vez." }, nav: { resources: "Recursos", decks: "Mis presentaciones", pricing: "Precios", signIn: "Entrar", language: "Idioma" },
  home: { badge: "TU PRIMERA PRESENTACIÓN ES GRATIS", title1: "De una idea inicial a una", title2: "presentación lista.", lead: "Cuéntanos qué necesitas o sube tus archivos. FreePPT crea una presentación clara y cuidada en minutos.", trust: ["Sin tarjeta", "PPTX editable", "HTML compartible"], eyebrow: "LA FORMA MÁS FÁCIL DE CREAR", stepsTitle: "Trae la idea. Nosotros hacemos las diapositivas.", steps: [{ title: "Danos el contexto", text: "Escribe una descripción o adjunta archivos Word, PowerPoint, Excel, PDF e imágenes." }, { title: "Entra en la cola", text: "La IA estructura la historia, redacta el contenido y diseña cada diapositiva." }, { title: "Descarga ambos formatos", text: "Obtén un PPTX editable y una presentación HTML adaptable." }] },
  generator: { placeholder: "Describe la presentación que quieres crear…", label: "Descripción de la presentación", attach: "Adjuntar archivos", drop: "o suéltalos aquí", limit: "Hasta 25 MB", remove: "Eliminar" }, modal: { close: "Cerrar", eyebrow: "ACCESO ANTICIPADO", title: "La generación llegará pronto.", text: "Estamos perfeccionando el motor. Únete y consigue gratis tu primera presentación cuando lancemos.", email: "tu@empresa.com", button: "Avísame", success: "Ya estás en la lista. ¡Te avisaremos!" },
  pricing: { ...en.pricing, badge: "PRECIOS SIMPLES POR CRÉDITOS", title1: "Una gran presentación.", title2: "Un precio claro.", lead: "Sin suscripciones. Empieza gratis y compra créditos cuando los necesites.", popular: "MÁS POPULAR", note: "Cada generación incluye PPTX y HTML. Los pagos llegarán pronto.", benefits: ["PPTX editable", "HTML compartible", "Archivos de hasta 25 MB"], plans: [{ name: "Primera presentación", price: "$0", unit: "una vez", detail: "Crea una presentación completa tras registrarte.", credits: "1 presentación", button: "Empezar gratis" }, { name: "Una presentación", price: "$5", unit: "por unidad", detail: "Paga solo cuando necesites otra.", credits: "1 presentación", button: "Crear" }, { name: "Paquete de 10", price: "$40", unit: "$4 / unidad", detail: "Para usuarios habituales.", credits: "10 · Ahorra 20 %", button: "Comprar 10" }, { name: "Paquete de 25", price: "$75", unit: "$3 / unidad", detail: "Para equipos y gran volumen.", credits: "25 · Ahorra 40 %", button: "Comprar 25" }] },
  queue: { ...en.queue, eyebrow: "MIS PRESENTACIONES", title: "Cola de generación", lead: "Sigue el progreso y descarga los dos formatos.", newDeck: "Nueva presentación", generating: "GENERANDO", ready: "LISTA", item1: "Estrategia trimestral de producto", item1Meta: "Generando · Añadida ahora", item2: "Tendencias de trabajo remoto 2026", item2Meta: "12 diapositivas · Terminada ayer", demo: "COLA DE DEMOSTRACIÓN", demoText: "El historial y las descargas estarán disponibles en el lanzamiento." },
  resources: { ...en.resources, title1: "Haz que cada presentación sea", title2: "más clara y potente.", lead: "Respuestas prácticas, flujos probados y guías sencillas para mejores diapositivas.", latest: "Última guía", section: "Fundamentos", type: "FUNDAMENTOS DE POWERPOINT · 8 MIN", articleTitle: "Tamaño de diapositiva en PowerPoint: dimensiones, píxeles y cómo cambiarlo", articleText: "Encuentra las dimensiones correctas para pantallas, impresión y redes sociales." },
  article: { ...en.article, home: "Inicio", resources: "Recursos", crumb: "Tamaño de diapositiva", kicker: "FUNDAMENTOS DE POWERPOINT", title1: "Tamaño de diapositiva:", title2: "dimensiones, píxeles y formatos", lead: "El tamaño estándar panorámico 16:9 es 13,333 × 7,5 pulgadas.", read: "8 min", updated: "Actualizado el 4 de septiembre de 2026", short: "Respuesta breve", shortText: "Elige 16:9 para casi todas las presentaciones nuevas. Usa 4:3 solo con equipos antiguos.", reference: "Referencia rápida de tamaños", referenceText: "PowerPoint guarda el tamaño en pulgadas o centímetros, no en píxeles.", format: "Formato", ratio: "Proporción", size: "Tamaño", use: "Uso", pixels: "Tamaño en píxeles", pixelsText: "No existe un tamaño fijo. 16:9 suele exportarse a 1280 × 720 o 1920 × 1080.", choose: "¿16:9 o 4:3?", chooseText: "Usa 16:9 salvo que el lugar o la plantilla exija 4:3. Se adapta a las pantallas modernas.", change: "Cómo cambiar el tamaño", changeText: "Abre Diseño → Tamaño de diapositiva, elige un ajuste y revisa todos los elementos.", faqTitle: "Preguntas frecuentes", ctaBadge: "PRIMERA PRESENTACIÓN GRATIS", ctaTitle: "Empieza con el formato correcto.", ctaText: "Describe tu presentación o sube un documento y recibe PPTX y HTML.", ctaButton: "Crear presentación" },
});

const ru = translated(en, {
  meta: { title: "FreePPT — бесплатный ИИ-генератор презентаций", description: "Превратите запрос или документ в готовую презентацию. Первая генерация бесплатно." }, nav: { resources: "Материалы", decks: "Мои презентации", pricing: "Цены", signIn: "Войти", language: "Язык" },
  home: { badge: "ПЕРВАЯ ПРЕЗЕНТАЦИЯ БЕСПЛАТНО", title1: "От черновой идеи до", title2: "готовой презентации.", lead: "Опишите задачу или загрузите материалы. FreePPT создаст ясную и аккуратную презентацию за несколько минут.", trust: ["Без карты", "Редактируемый PPTX", "HTML для публикации"], eyebrow: "САМЫЙ ПРОСТОЙ СПОСОБ СОЗДАТЬ ПРЕЗЕНТАЦИЮ", stepsTitle: "Ваша идея — наши слайды.", steps: [{ title: "Добавьте контекст", text: "Введите описание или прикрепите Word, PowerPoint, Excel, PDF и изображения." }, { title: "Встаньте в очередь", text: "ИИ выстроит историю, напишет текст и оформит каждый слайд." }, { title: "Скачайте два формата", text: "Получите редактируемый PPTX и адаптивную HTML-презентацию." }] },
  generator: { placeholder: "Опишите презентацию, которую хотите создать…", label: "Описание презентации", attach: "Прикрепить файлы", drop: "или перетащите сюда", limit: "До 25 МБ", remove: "Удалить" }, modal: { close: "Закрыть", eyebrow: "РАННИЙ ДОСТУП", title: "Генерация скоро появится.", text: "Мы завершаем работу над движком. Запишитесь и получите первую презентацию бесплатно после запуска.", email: "you@company.com", button: "Сообщить мне", success: "Вы в списке. Мы свяжемся с вами!" },
  pricing: { ...en.pricing, badge: "ПРОСТАЯ ОПЛАТА ЗА ГЕНЕРАЦИИ", title1: "Отличная презентация.", title2: "Понятная цена.", lead: "Без подписки. Начните бесплатно и покупайте генерации по мере необходимости.", popular: "ПОПУЛЯРНО", note: "Каждая генерация включает PPTX и HTML. Оплата скоро появится.", benefits: ["Редактируемый PPTX", "HTML для публикации", "Файлы до 25 МБ"], plans: [{ name: "Первая презентация", price: "$0", unit: "один раз", detail: "Создайте презентацию после регистрации.", credits: "1 генерация", button: "Начать бесплатно" }, { name: "Одна презентация", price: "$5", unit: "за генерацию", detail: "Платите только когда это нужно.", credits: "1 генерация", button: "Создать" }, { name: "Пакет из 10", price: "$40", unit: "$4 / генерация", detail: "Для регулярной работы.", credits: "10 · Экономия 20%", button: "Купить 10" }, { name: "Пакет из 25", price: "$75", unit: "$3 / генерация", detail: "Для команд и больших объёмов.", credits: "25 · Экономия 40%", button: "Купить 25" }] },
  queue: { ...en.queue, eyebrow: "МОИ ПРЕЗЕНТАЦИИ", title: "Очередь генерации", lead: "Следите за процессом и скачивайте оба формата.", newDeck: "Новая презентация", generating: "СОЗДАЁТСЯ", ready: "ГОТОВО", item1: "Квартальная продуктовая стратегия", item1Meta: "Создаётся · Добавлено сейчас", item2: "Тренды удалённой работы 2026", item2Meta: "12 слайдов · Готово вчера", demo: "ДЕМО-ОЧЕРЕДЬ", demoText: "История и скачивание появятся после запуска." },
  resources: { ...en.resources, title1: "Сделайте каждую презентацию", title2: "яснее и убедительнее.", lead: "Практические ответы, проверенные процессы и понятные руководства.", latest: "Новый материал", section: "Основы презентаций", type: "ОСНОВЫ POWERPOINT · 8 МИН", articleTitle: "Размер слайда PowerPoint: размеры, пиксели и изменение", articleText: "Подберите размер для экранов, печати и социальных сетей." },
  article: { ...en.article, home: "Главная", resources: "Материалы", crumb: "Размер слайда", kicker: "ОСНОВЫ POWERPOINT", title1: "Размер слайда PowerPoint:", title2: "размеры, пиксели и форматы", lead: "Стандартный размер 16:9 — 13,333 × 7,5 дюйма.", read: "8 мин", updated: "Обновлено 4 сентября 2026", short: "Краткий ответ", shortText: "Для новых презентаций выбирайте 16:9. Формат 4:3 нужен в основном для старого оборудования.", reference: "Таблица размеров", referenceText: "PowerPoint хранит размер в дюймах или сантиметрах, а не в пикселях.", format: "Формат", ratio: "Соотношение", size: "Размер", use: "Применение", pixels: "Размер в пикселях", pixelsText: "Фиксированного размера нет. 16:9 обычно экспортируют в 1280 × 720 или 1920 × 1080.", choose: "16:9 или 4:3?", chooseText: "Используйте 16:9, если площадка или шаблон не требуют 4:3. Этот формат подходит современным экранам.", change: "Как изменить размер", changeText: "Откройте Дизайн → Размер слайда, выберите вариант и проверьте расположение всех элементов.", faqTitle: "Частые вопросы", ctaBadge: "ПЕРВАЯ ПРЕЗЕНТАЦИЯ БЕСПЛАТНО", ctaTitle: "Начните с правильного формата.", ctaText: "Опишите задачу или загрузите документ и получите PPTX и HTML.", ctaButton: "Создать презентацию" },
});

export const translations: Record<Locale, Translation> = { en, "zh-CN": zhCN, "zh-TW": zhTW, ja, ko, fr, es, ru };
