import type { PptTemplate } from "@/lib/templates";

export const templates20260910: PptTemplate[] = [
  {
    slug: "restaurant-launch-business-plan",
    name: "Free Restaurant Launch Business Plan PowerPoint Template",
    shortName: "Restaurant Launch Business Plan",
    category: "Business Plan",
    categorySlug: "business-plan",
    description: "A restaurant business plan template for presenting the dining concept, local demand, menu economics, service model, launch budget, and first-year milestones.",
    longDescription: "This free restaurant launch business plan PowerPoint template turns a hospitality concept into an investor-ready operating story. Eight editable slides cover the customer occasion, concept, menu architecture, neighborhood demand, unit economics, service system, launch budget, and opening milestones. Its original menu-led visual system uses terracotta, olive, warm cream, dotted leaders, and receipt-like information bands built only from native PowerPoint shapes. No source photography, illustrations, decorative assets, text, charts, or recognizable layouts are reused.",
    accent: "C95B3D", dark: "26352B", soft: "F3E4C7",
    tags: ["Restaurant business plan", "Hospitality", "Opening plan", "16:9"],
    slides: [
      { eyebrow: "RESTAURANT PLAN · 2026", title: "A neighborhood table designed for repeat rituals", body: "A focused opening plan connecting occasion, menu, service, economics, and local demand." },
      { eyebrow: "01 · OCCASION", title: "Win one dining moment before expanding the menu", body: "Define the guest, occasion, current compromise, frequency, and reason to choose this concept.", stat: "3 nights" },
      { eyebrow: "02 · CONCEPT", title: "Make the promise visible from doorway to check", body: "Connect positioning, atmosphere, service pace, signature offer, and the feeling guests remember." },
      { eyebrow: "03 · MENU", title: "A compact menu protects quality and margin", body: "Organize anchors, complements, beverages, prep overlap, price points, and seasonal rotation." },
      { eyebrow: "04 · DEMAND", title: "Size the neighborhood from observable behavior", body: "Use footfall, occasions, trade area, competitive supply, conversion, and realistic seat capacity.", stat: "1.8 mi" },
      { eyebrow: "05 · ECONOMICS", title: "Contribution begins with every plate", body: "Show average check, ingredient cost, labor, occupancy, waste, and sensitivity as placeholder assumptions." },
      { eyebrow: "06 · SERVICE", title: "Design the shift before opening the doors", body: "Map reservations, prep, handoffs, quality checks, table turns, recovery, and closing routines." },
      { eyebrow: "07 · OPENING", title: "Release capital only when evidence is ready", body: "Sequence permits, build, hiring, soft opening, launch, and the first operating review.", stat: "$180K" },
    ],
    included: ["Plan cover", "Dining occasion", "Restaurant concept", "Menu architecture", "Local demand", "Unit economics", "Service model", "Opening milestones"],
    bestFor: ["Independent restaurants", "Hospitality investors", "Pop-up expansion", "Restaurant opening plans"],
  },
  {
    slug: "deep-tech-startup-pitch-deck",
    name: "Free Deep Tech Startup Pitch Deck PowerPoint Template",
    shortName: "Deep Tech Startup Pitch Deck",
    category: "Startup Pitch Deck",
    categorySlug: "pitch-deck",
    description: "A deep-tech startup pitch deck for explaining a costly technical constraint, breakthrough, validation evidence, beachhead market, defensibility, roadmap, and funding ask.",
    longDescription: "This free deep tech startup pitch deck PowerPoint template is structured for founders who must make a complex technical advantage understandable without diluting the evidence. It covers the constraint, breakthrough, system, validation, beachhead, economics, defensibility, and funding milestone. The original circuit-board visual language uses midnight violet, cyan traces, amber signal nodes, and modular validation cards made from editable native shapes. It does not reproduce the reference template's geometry, backgrounds, icons, illustrations, copy, or slide sequence.",
    accent: "53D7E8", dark: "17142D", soft: "E8E3F6",
    tags: ["Deep tech", "Startup pitch deck", "Seed funding", "16:9"],
    slides: [
      { eyebrow: "DEEP TECH · SEED", title: "Move precision sensing from the lab into daily operations", body: "A validated platform built for faster decisions in demanding physical environments." },
      { eyebrow: "01 · CONSTRAINT", title: "Critical measurements arrive too late to change outcomes", body: "Show the workflow, delay, failure cost, affected operator, and why existing options fall short.", stat: "36 hrs" },
      { eyebrow: "02 · BREAKTHROUGH", title: "A new sensing stack converts noise into a useful signal", body: "Explain the technical leap, customer consequence, boundary conditions, and present maturity." },
      { eyebrow: "03 · SYSTEM", title: "Hardware, models, and workflow operate as one product", body: "Trace capture, processing, inference, review, action, feedback, and system ownership." },
      { eyebrow: "04 · VALIDATION", title: "Representative tests show a repeatable advantage", body: "Compare baseline, protocol, sample, result, uncertainty, failure cases, and next validation gate.", stat: "4.6×" },
      { eyebrow: "05 · BEACHHEAD", title: "Enter where delay is expensive and proof is accessible", body: "Define the first buyer, use case, reachable accounts, buying trigger, and adjacent expansion." },
      { eyebrow: "06 · MOAT", title: "The advantage compounds through deployment learning", body: "Connect proprietary methods, data rights, integration depth, certification, know-how, and switching cost." },
      { eyebrow: "07 · ASK", title: "Fund the evidence required for commercial scale", body: "State capital, runway, engineering, validation, pilot, regulatory, and revenue milestones.", stat: "$3.2M" },
    ],
    included: ["Pitch cover", "Technical constraint", "Breakthrough", "System architecture", "Validation", "Beachhead market", "Defensibility", "Funding ask"],
    bestFor: ["Hardware startups", "Scientific founders", "Industrial technology", "Deep-tech fundraising"],
  },
  {
    slug: "retro-company-profile-presentation",
    name: "Free Retro Company Profile PowerPoint Template",
    shortName: "Retro Company Profile",
    category: "Company Profile",
    categorySlug: "company-profile",
    description: "A warm retro company profile for introducing a distinctive brand, operating facts, offers, customer proof, principles, people, and partnership fit.",
    longDescription: "This free retro company profile PowerPoint template presents a modern organization through a memorable but practical brand system. Eight editable slides cover the promise, company facts, customer context, offers, operating model, selected proof, working principles, and next conversation. Its original capsule visual language uses oxblood, apricot, mustard, cream, concentric ovals, and compact fact tiles made with native PowerPoint shapes. No grunge assets, stickers, source typography, imagery, copy, or recognizable layouts are used.",
    accent: "D06B45", dark: "4A1F2A", soft: "F1D69E",
    tags: ["Company profile", "Retro", "Brand presentation", "16:9"],
    slides: [
      { eyebrow: "COMPANY PROFILE · 2026", title: "Thoughtful systems for brands people choose again", body: "Our identity, practice, proof, principles, and the work we are ready to do next." },
      { eyebrow: "01 · PROMISE", title: "We turn complicated offers into confident choices", body: "Name the audience, recurring decision, useful outcome, and standard the company owns.", stat: "1 promise" },
      { eyebrow: "02 · FACTS", title: "Focused scale keeps senior expertise close", body: "Present verified locations, years, clients, disciplines, capacity, and ownership." },
      { eyebrow: "03 · CONTEXT", title: "Customer expectations move faster than internal systems", body: "Describe the market shift, friction, business consequence, and reason for action." },
      { eyebrow: "04 · OFFERS", title: "Three connected offers create one coherent experience", body: "Group capabilities by outcome with clear scope, deliverables, timing, and accountable leads.", stat: "3 offers" },
      { eyebrow: "05 · METHOD", title: "A steady rhythm moves from evidence to adoption", body: "Show diagnose, frame, make, test, launch, learn, and improve as an owned workflow." },
      { eyebrow: "06 · PROOF", title: "Selected outcomes reveal how the practice works", body: "State client context, baseline, intervention, measured result, period, and limitations." },
      { eyebrow: "07 · FIT", title: "Begin where clarity would change a decision", body: "Close with project fit, working mode, availability, contact, and one specific invitation.", stat: "Q4" },
    ],
    included: ["Profile cover", "Company promise", "Key facts", "Customer context", "Service offers", "Working method", "Selected proof", "Partnership CTA"],
    bestFor: ["Creative companies", "Brand introductions", "Agency credentials", "Partnership meetings"],
  },
  {
    slug: "event-marketing-plan-presentation",
    name: "Free Event Marketing Plan PowerPoint Template",
    shortName: "Event Marketing Plan",
    category: "Marketing Plan",
    categorySlug: "marketing",
    description: "An event marketing plan template for aligning the audience, attendance promise, channel roles, 12-week promotion plan, partners, budget, and measurement.",
    longDescription: "This free event marketing plan PowerPoint template helps teams connect an attendance target to a disciplined campaign calendar. Its eight editable slides cover the event brief, audience, value proposition, channel jobs, promotional flighting, partner activation, budget, and measurement. The original ticket-stub design combines plum, coral, mint, warm white, perforated rules, and time-coded blocks created from native PowerPoint shapes. It does not reuse the source spreadsheets, timelines, labels, graphics, copy, or page arrangements.",
    accent: "F2645A", dark: "35203F", soft: "DFF0DF",
    tags: ["Event marketing", "Marketing plan", "Promotion timeline", "16:9"],
    slides: [
      { eyebrow: "EVENT MARKETING · 12 WEEKS", title: "Turn a calendar date into a reason to gather", body: "An attendance plan connecting relevance, reach, partners, timing, and measurable action." },
      { eyebrow: "01 · BRIEF", title: "Define the attendance behavior the event must create", body: "Set audience, capacity, paid or free model, commercial goal, timing, and constraints.", stat: "750 seats" },
      { eyebrow: "02 · AUDIENCE", title: "Prioritize communities with a shared reason to attend", body: "Map roles, motivations, objections, trusted sources, decision timing, and accessibility needs." },
      { eyebrow: "03 · PROMISE", title: "Sell the change participants take home", body: "Build the event promise, proof, program pillars, speaker role, and action hierarchy." },
      { eyebrow: "04 · CHANNELS", title: "Give each channel one job in the attendance journey", body: "Assign awareness, validation, capture, conversion, reminder, and advocacy roles.", stat: "6 roles" },
      { eyebrow: "05 · FLIGHTING", title: "Use twelve weeks to build belief, urgency, and readiness", body: "Sequence announce, educate, prove, convert, prepare, live coverage, and follow-up." },
      { eyebrow: "06 · PARTNERS", title: "Make partner reach useful to both audiences", body: "Define partner fit, asset exchange, ownership, tracking, deadlines, and shared value." },
      { eyebrow: "07 · SCORECARD", title: "Measure attendance quality—not registrations alone", body: "Track qualified reach, conversion, show rate, engagement, pipeline, cost, and next action.", stat: "$42 CPA" },
    ],
    included: ["Plan cover", "Event brief", "Target audience", "Attendance promise", "Channel roles", "12-week flighting", "Partner activation", "Measurement scorecard"],
    bestFor: ["Conferences", "Webinars", "Community events", "Event campaign planning"],
  },
  {
    slug: "road-construction-project-proposal",
    name: "Free Road Construction Project Proposal PowerPoint Template",
    shortName: "Road Construction Project Proposal",
    category: "Project Proposal",
    categorySlug: "project-proposal",
    description: "A road construction proposal for communicating the mobility problem, corridor concept, scope, staging, stakeholder plan, budget, controls, and approval gate.",
    longDescription: "This free road construction project proposal PowerPoint template gives public works and infrastructure teams a clear decision structure. Eight editable slides cover corridor need, target outcome, route concept, project scope, construction staging, stakeholder coordination, budget and risk controls, and the approval request. Its original lane-marker visual system uses asphalt charcoal, safety amber, off-white, solid and dashed route bands, and permit-style cards built from native PowerPoint shapes. It does not use the source photos, vehicle imagery, charts, maps, icons, text, or slide layouts.",
    accent: "F1A52B", dark: "25292C", soft: "E9E4D8",
    tags: ["Construction proposal", "Infrastructure", "Road project", "16:9"],
    slides: [
      { eyebrow: "CORRIDOR PROPOSAL · GATE 01", title: "Improve movement while keeping the district connected", body: "A staged road proposal balancing safety, access, delivery, cost, and public confidence." },
      { eyebrow: "01 · NEED", title: "The corridor no longer serves present demand safely", body: "Quantify delay, conflict points, access, maintenance burden, affected users, and urgency.", stat: "18 min" },
      { eyebrow: "02 · OUTCOME", title: "Success means safer and more reliable movement", body: "Define travel, safety, access, resilience, construction, and community outcome measures." },
      { eyebrow: "03 · CONCEPT", title: "A complete corridor separates competing movements", body: "Explain alignment, intersections, transit, walking, cycling, drainage, utilities, and boundaries." },
      { eyebrow: "04 · SCOPE", title: "Package the work around verifiable handoffs", body: "List design, enabling works, civil works, systems, testing, exclusions, and owner obligations.", stat: "6 packages" },
      { eyebrow: "05 · STAGING", title: "Maintain access while the route changes", body: "Sequence surveys, utilities, temporary traffic, zones, commissioning, and reinstatement." },
      { eyebrow: "06 · CONTROLS", title: "Put safety, cost, environment, and change on one register", body: "Assign leading indicators, thresholds, mitigations, owners, reporting, and escalation." },
      { eyebrow: "07 · GATE", title: "Approve detailed design against stated conditions", body: "Close with budget range, funding, decision owner, dependencies, and next evidence gate.", stat: "$24M" },
    ],
    included: ["Proposal cover", "Corridor need", "Target outcomes", "Route concept", "Scope packages", "Construction staging", "Project controls", "Approval gate"],
    bestFor: ["Infrastructure proposals", "Public works", "Transport projects", "Construction briefings"],
  },
  {
    slug: "weekly-sales-report-presentation",
    name: "Free Weekly Sales Report PowerPoint Template",
    shortName: "Weekly Sales Report",
    category: "Sales Report",
    categorySlug: "sales-report",
    description: "A weekly sales report template for reviewing bookings, stage movement, activity quality, regional signals, forecast changes, blockers, and owned next actions.",
    longDescription: "This free weekly sales report PowerPoint template helps revenue teams run a short, decision-focused operating review. Eight editable slides cover the weekly headline, bookings bridge, funnel movement, activity quality, regional performance, forecast changes, blockers, and commitments. The original week-grid visual system uses charcoal, lime, sand, seven-day tabs, small multiples, and compact scorecards built entirely from native PowerPoint shapes. No source dashboard, charts, tables, fonts, data, copy, or page compositions are reproduced.",
    accent: "C8E34D", dark: "202829", soft: "ECE4CE",
    tags: ["Weekly sales report", "Revenue operations", "Sales dashboard", "16:9"],
    slides: [
      { eyebrow: "WEEKLY SALES · W37", title: "Bookings advanced while late-stage timing moved", body: "A seven-day operating view of revenue, pipeline, activity, confidence, and ownership." },
      { eyebrow: "01 · HEADLINE", title: "The week finished above pace with one timing risk", body: "Compare bookings, target, prior week, quarter pace, mix, and the cause behind variance.", stat: "108%" },
      { eyebrow: "02 · BRIDGE", title: "Expansion and one new logo drove the gain", body: "Separate opening pipeline, created, advanced, won, slipped, lost, and closing position." },
      { eyebrow: "03 · FUNNEL", title: "Discovery moved faster; proposals need stronger next steps", body: "Show entries, exits, conversion, age, velocity, and verified customer actions." },
      { eyebrow: "04 · ACTIVITY", title: "Quality conversations matter more than raw volume", body: "Connect calls, meetings, decision-makers, follow-ups, next actions, and opportunity movement.", stat: "23 meets" },
      { eyebrow: "05 · REGIONS", title: "West leads on velocity while East holds larger value", body: "Compare consistent measures across territories and name the operating explanation." },
      { eyebrow: "06 · FORECAST", title: "Commit holds, but two dates require evidence", body: "Present weekly movement, commit, upside, risks, assumptions, and next confirmation events." },
      { eyebrow: "07 · ACTIONS", title: "Close the review with owned moves for next week", body: "Assign customer action, rep, support needed, signal of progress, and review date.", stat: "5 owners" },
    ],
    included: ["Weekly cover", "Headline scorecard", "Bookings bridge", "Funnel movement", "Activity quality", "Regional view", "Forecast change", "Owned actions"],
    bestFor: ["Weekly sales meetings", "Revenue operations", "Regional managers", "Pipeline reviews"],
  },
  {
    slug: "grammar-lesson-plan-presentation",
    name: "Free Grammar Lesson Plan PowerPoint Template",
    shortName: "Grammar Lesson Plan",
    category: "Lesson Plan",
    categorySlug: "education",
    description: "A grammar lesson plan template for sequencing an inquiry question, learning target, sentence noticing, explicit model, guided practice, transfer, and exit check.",
    longDescription: "This free grammar lesson plan PowerPoint template turns language conventions into an active pattern-finding lesson. Eight editable slides move from the inquiry question and objectives to noticing, sentence anatomy, teacher modeling, guided practice, transfer writing, and an exit check. Its original syntax-tree visual system uses ink blue, coral, paper cream, connector lines, bracket forms, and movable word tiles made from native PowerPoint shapes. It avoids the source template's retro backgrounds, photos, geometric decorations, text, fonts, and layouts.",
    accent: "E96951", dark: "213A5A", soft: "F2E4C9",
    tags: ["Grammar lesson", "English teacher", "Lesson plan", "16:9"],
    slides: [
      { eyebrow: "GRAMMAR LAB · 45 MIN", title: "How does sentence structure change emphasis?", body: "Notice, name, move, test, explain, and apply one useful language pattern." },
      { eyebrow: "01 · TARGET", title: "Make the language move and its purpose visible", body: "State what learners will identify, manipulate, explain, and use by the end.", stat: "4 goals" },
      { eyebrow: "02 · NOTICE", title: "Begin with two sentences that create different effects", body: "Invite comparison, annotation, prediction, and discussion before naming the rule." },
      { eyebrow: "03 · ANATOMY", title: "Map how each phrase contributes to meaning", body: "Use movable word groups to show function, relationship, optionality, and punctuation." },
      { eyebrow: "04 · MODEL", title: "Think aloud while testing alternative structures", body: "Reveal cues, choices, tradeoffs, a misconception, and how the reader experience changes.", stat: "3 moves" },
      { eyebrow: "05 · PRACTICE", title: "Rebuild sentences with one controlled change", body: "Move from whole-class sorting to paired transformation and independent explanation." },
      { eyebrow: "06 · TRANSFER", title: "Use the pattern in writing that matters", body: "Apply the structure to a real paragraph, then justify the choice against the intended effect." },
      { eyebrow: "07 · EXIT", title: "Check recognition, control, and reasoning separately", body: "Collect one identification, one revision, one explanation, and the next teaching decision.", stat: "3 checks" },
    ],
    included: ["Lesson cover", "Learning target", "Sentence noticing", "Sentence anatomy", "Teacher model", "Guided practice", "Transfer writing", "Exit check"],
    bestFor: ["English classes", "Secondary teachers", "Writing workshops", "Language instruction"],
  },
  {
    slug: "monochrome-thesis-defense-presentation",
    name: "Free Monochrome Thesis Defense PowerPoint Template",
    shortName: "Monochrome Thesis Defense",
    category: "Thesis Defense",
    categorySlug: "thesis-defense",
    description: "A monochrome thesis defense template for presenting a precise question, literature gap, hypotheses, method, statistical evidence, interpretation, limitations, and contribution.",
    longDescription: "This free monochrome thesis defense PowerPoint template gives quantitative research a restrained, committee-ready structure. Eight editable slides cover the research question, gap, hypotheses, design, results, interpretation, limitations, and contribution. Its original statistical-monograph visual system uses black, bone white, signal red, confidence bands, citation rails, and typeset evidence blocks made with native PowerPoint shapes. It does not copy the source template's page layouts, graphics, typography, text, charts, or decorative elements.",
    accent: "D64B3B", dark: "161616", soft: "E8E5DE",
    tags: ["Thesis defense", "Monochrome", "Quantitative research", "16:9"],
    slides: [
      { eyebrow: "THESIS DEFENSE · 2026", title: "When does transparent ownership improve team decisions?", body: "A quantitative field study of traceability, response time, and decision quality." },
      { eyebrow: "01 · QUESTION", title: "The study tests one bounded relationship", body: "Define exposure, outcome, population, setting, period, and the claim the design can support.", stat: "1 question" },
      { eyebrow: "02 · GAP", title: "Prior evidence measures access more often than accountability", body: "Synthesize agreement, conflict, missing mechanism, measurement gap, and research opportunity." },
      { eyebrow: "03 · HYPOTHESES", title: "Three predictions connect visibility to behavior", body: "State direction, mechanism, moderator, observable measure, and falsifying evidence." },
      { eyebrow: "04 · DESIGN", title: "A preregistered panel design tests change over time", body: "Present sampling, assignment, measures, procedure, ethics, exclusions, and analysis plan.", stat: "n=384" },
      { eyebrow: "05 · RESULTS", title: "Ownership cues improved traceability in the sample", body: "Report estimate, interval, model, robustness, missingness, and planned versus exploratory results." },
      { eyebrow: "06 · INTERPRET", title: "The effect supports the mechanism within a narrow setting", body: "Separate observation, inference, practical meaning, alternative explanation, and uncertainty." },
      { eyebrow: "07 · CONTRIBUTION", title: "The contribution is a measurable theory of ownership cues", body: "Close with theory, practice, limitations, replication, open questions, and the defended claim.", stat: "95% CI" },
    ],
    included: ["Defense cover", "Research question", "Literature gap", "Hypotheses", "Research design", "Statistical results", "Interpretation", "Contribution and limits"],
    bestFor: ["Quantitative theses", "PhD defenses", "Research seminars", "Academic committees"],
  },
  {
    slug: "patient-recovery-clinical-case",
    name: "Free Patient Recovery Clinical Case PowerPoint Template",
    shortName: "Patient Recovery Clinical Case",
    category: "Clinical Case",
    categorySlug: "medical",
    description: "A patient recovery case template for presenting de-identified history, functional baseline, assessment, goals, intervention stages, response, safety plan, and learning points.",
    longDescription: "This free patient recovery clinical case PowerPoint template supports a chronological, education-only case discussion without implying clinical advice. Eight editable slides cover the presenting concern, functional baseline, focused assessment, goals, intervention pathway, observed response, safety and follow-up, and learning points. Its original care-path visual system uses burgundy, blush, navy, staged progress markers, and rounded observation cards made with native PowerPoint shapes. It does not reuse source illustrations, medical imagery, waves, icons, copy, clinical claims, or page compositions.",
    accent: "A9415B", dark: "243448", soft: "F2DDE0",
    tags: ["Clinical case", "Patient recovery", "Medical education", "16:9"],
    slides: [
      { eyebrow: "CLINICAL CASE · EDUCATION ONLY", title: "A staged recovery plan guided by function and response", body: "A de-identified placeholder case for chronology, reasoning, safety, and reflection." },
      { eyebrow: "01 · CONCERN", title: "Begin with the functional change that prompted evaluation", body: "Summarize onset, trajectory, context, severity, relevant history, and meaningful negatives.", stat: "Day 0" },
      { eyebrow: "02 · BASELINE", title: "Describe what the person could and could not do", body: "Separate symptoms, activity, participation, environment, support, and patient priorities." },
      { eyebrow: "03 · ASSESS", title: "Prioritize findings that change the working explanation", body: "Present focused observations, measures, red flags, uncertainty, and the differential." },
      { eyebrow: "04 · GOALS", title: "Translate priorities into observable recovery goals", body: "Set function, time horizon, measure, shared decision, stopping rule, and review point.", stat: "3 goals" },
      { eyebrow: "05 · PATHWAY", title: "Progress through stages only when criteria are met", body: "Connect education, supported activity, graded load, monitoring, adaptation, and escalation." },
      { eyebrow: "06 · RESPONSE", title: "Show change over time without overstating causality", body: "Compare baseline and follow-up observations, adherence, context, variation, and uncertainty." },
      { eyebrow: "07 · LEARNING", title: "Separate case-specific outcome from transferable learning", body: "Close with safety, follow-up, limitations, unresolved questions, and teaching points.", stat: "3 points" },
    ],
    included: ["Case cover", "Presenting concern", "Functional baseline", "Assessment", "Recovery goals", "Intervention pathway", "Observed response", "Safety and learning"],
    bestFor: ["Medical education", "Rehabilitation case review", "Clinical teaching", "De-identified case conferences"],
  },
  {
    slug: "ai-governance-presentation",
    name: "Free AI Governance PowerPoint Template",
    shortName: "AI Governance",
    category: "AI & Technology",
    categorySlug: "artificial-intelligence",
    description: "An AI governance template for aligning system inventory, risk tiers, decision rights, lifecycle gates, evidence, monitoring, incident response, and rollout priorities.",
    longDescription: "This free AI governance PowerPoint template helps cross-functional teams turn principles into an inspectable operating model. Eight editable slides cover the governance mandate, AI inventory, risk classification, decision rights, lifecycle gates, required evidence, monitoring and incidents, and a phased rollout. Its original decision-gate visual language uses warm white, black, electric orange, cobalt, check rails, and approval cards made with native PowerPoint shapes. It does not reproduce the reference roadmap's pillars, initiative cards, content, example, timeline, icons, or layout.",
    accent: "FF6A35", dark: "191919", soft: "E8E4D8",
    tags: ["AI governance", "Responsible AI", "Technology strategy", "16:9"],
    slides: [
      { eyebrow: "AI GOVERNANCE · OPERATING MODEL", title: "Move AI decisions through evidence, ownership, and review", body: "A practical governance system for useful innovation with proportionate control." },
      { eyebrow: "01 · MANDATE", title: "Govern decisions and consequences—not technology labels", body: "Define purpose, scope, principles, authority, regulatory context, and success measures.", stat: "1 mandate" },
      { eyebrow: "02 · INVENTORY", title: "Know every AI system, use case, owner, and dependency", body: "Record purpose, users, decisions, data, provider, model, integrations, status, and review date." },
      { eyebrow: "03 · RISK", title: "Classification determines the depth of evidence and review", body: "Assess impact, autonomy, sensitivity, reversibility, exposure, uncertainty, and obligations." },
      { eyebrow: "04 · RIGHTS", title: "Make decision rights explicit across the lifecycle", body: "Assign proposal, domain, data, engineering, security, legal, approval, operation, and audit roles.", stat: "8 roles" },
      { eyebrow: "05 · GATES", title: "Progress only when evidence satisfies the next gate", body: "Sequence intake, design, evaluation, release, monitoring, material change, and retirement." },
      { eyebrow: "06 · MONITOR", title: "Connect production signals to owned responses", body: "Track quality, harm, bias, drift, privacy, misuse, reliability, complaints, and escalation." },
      { eyebrow: "07 · ROLLOUT", title: "Establish visibility before scaling governance depth", body: "Phase inventory, triage, high-risk controls, operating cadence, automation, and assurance.", stat: "90 days" },
    ],
    included: ["Governance cover", "Mandate", "AI inventory", "Risk tiers", "Decision rights", "Lifecycle gates", "Monitoring and incidents", "Rollout plan"],
    bestFor: ["AI governance programs", "Responsible AI reviews", "Technology leadership", "Risk committees"],
  },
  {
    slug: "architecture-portfolio-presentation",
    name: "Free Architecture Portfolio PowerPoint Template",
    shortName: "Architecture Portfolio",
    category: "Creative Portfolio",
    categorySlug: "portfolio",
    description: "An architecture portfolio template for presenting a design position, selected projects, site response, spatial concept, material system, process, outcomes, and contact.",
    longDescription: "This free architecture portfolio PowerPoint template gives projects a rigorous editorial frame without requiring external assets. Eight editable slides cover the practice thesis, selected work, project context, spatial concept, material system, design process, outcomes, and contact. Its original planar visual system uses concrete gray, rust, charcoal, cropped native-shape placeholders, scale bars, and offset plan lines. It does not use the source photographs, floor plans, schematics, icons, geometric decorations, fonts, wording, or recognizable layouts.",
    accent: "B8583D", dark: "303336", soft: "DDD9D1",
    tags: ["Architecture portfolio", "Creative portfolio", "Design projects", "16:9"],
    slides: [
      { eyebrow: "ARCHITECTURE PORTFOLIO · 2026", title: "Spaces shaped by climate, movement, and daily use", body: "Selected work across public, residential, and adaptive-reuse contexts." },
      { eyebrow: "01 · POSITION", title: "Architecture begins with the life a place must support", body: "State the practice position, contexts, scales, collaborators, and principles connecting the work.", stat: "7 years" },
      { eyebrow: "02 · INDEX", title: "Curate projects around relevant range and depth", body: "Introduce role, type, place, stage, collaborators, constraints, and one outcome for each." },
      { eyebrow: "03 · SITE", title: "A civic edge becomes a shaded public room", body: "Frame climate, movement, history, access, constraints, stakeholders, and the design question." },
      { eyebrow: "04 · SPACE", title: "Three linked volumes organize a gradual threshold", body: "Explain massing, circulation, program, light, view, accessibility, and moments of pause.", stat: "3 volumes" },
      { eyebrow: "05 · MATERIAL", title: "A restrained material system supports repair and aging", body: "Present structure, envelope, finish, sourcing, maintenance, carbon assumptions, and detail intent." },
      { eyebrow: "06 · PROCESS", title: "Models make tradeoffs visible before commitments harden", body: "Show research, alternatives, critique, coordination, prototyping, review, and iteration." },
      { eyebrow: "07 · CONTACT", title: "Invite the next project through a clear fit", body: "Close with project types, role, availability, location, collaborators, and contact details.", stat: "Q1" },
    ],
    included: ["Portfolio cover", "Design position", "Project index", "Site response", "Spatial concept", "Material system", "Design process", "Contact"],
    bestFor: ["Architecture portfolios", "Design interviews", "Studio credentials", "Project submissions"],
  },
  {
    slug: "release-train-product-roadmap",
    name: "Free Release Train Product Roadmap PowerPoint Template",
    shortName: "Release Train Product Roadmap",
    category: "Product Roadmap",
    categorySlug: "product-roadmap",
    description: "A release-train product roadmap for aligning customer outcomes, evidence, workstreams, release stations, dependencies, readiness gates, measures, and the next review.",
    longDescription: "This free release train product roadmap PowerPoint template turns delivery sequencing into an evidence-led operating conversation. Eight editable slides cover the target outcome, evidence, strategic tracks, release stations, dependencies, readiness gates, success measures, and review cadence. Its original transit-map visual system uses midnight black, amber, sky blue, parallel route lines, station nodes, and platform cards built from native PowerPoint shapes. It does not reproduce source timeline designs, infographic components, icons, wording, colors, or page arrangements.",
    accent: "F2B134", dark: "181D23", soft: "DCEAF0",
    tags: ["Product roadmap", "Release planning", "Product management", "16:9"],
    slides: [
      { eyebrow: "RELEASE TRAIN · H1 2027", title: "Sequence releases around customer learning", body: "A roadmap connecting outcomes, evidence, tracks, gates, dependencies, and decisions." },
      { eyebrow: "01 · OUTCOME", title: "The destination is a changed customer behavior", body: "Define the user, moment, action, speed, quality, business value, and guardrail.", stat: "< 2 min" },
      { eyebrow: "02 · EVIDENCE", title: "Signals determine which route deserves investment", body: "Combine behavior, interviews, support, commercial context, reliability, and technical learning." },
      { eyebrow: "03 · TRACKS", title: "Three outcome tracks keep initiatives connected", body: "Group discovery, activation, trust, platform, and go-to-market work around owned results." },
      { eyebrow: "04 · STATIONS", title: "Each release station delivers value and tests a belief", body: "Show audience, availability, capability, hypothesis, success signal, and expansion rule.", stat: "4 stations" },
      { eyebrow: "05 · LINKS", title: "Expose cross-track dependencies before dates move", body: "Map data, platform, research, policy, enablement, staffing, vendor, and owner links." },
      { eyebrow: "06 · READY", title: "Readiness gates protect quality without freezing learning", body: "Define evaluation, reliability, privacy, support, commercial, rollback, and launch evidence." },
      { eyebrow: "07 · REVIEW", title: "Use the roadmap review to reroute investment", body: "Compare expected and observed signals, update confidence, record choices, and own next actions.", stat: "30 days" },
    ],
    included: ["Roadmap cover", "Customer outcome", "Evidence signals", "Outcome tracks", "Release stations", "Dependencies", "Readiness gates", "Review cadence"],
    bestFor: ["Release planning", "Product leadership", "Cross-functional roadmaps", "Portfolio reviews"],
  },
];
