import type { PptTemplate, TemplateSlide } from "@/lib/templates";

type DeckSeed = Omit<PptTemplate, "slides"> & {
  cover: [string, string, string];
  story: Array<[string, string, string, string?]>;
};

function deck(seed: DeckSeed): PptTemplate {
  const slides: TemplateSlide[] = [
    { eyebrow: seed.cover[0], title: seed.cover[1], body: seed.cover[2] },
    ...seed.story.map(([eyebrow, title, body, stat]) => ({ eyebrow, title, body, stat })),
  ];
  return { ...seed, slides };
}

export const templates20260910Round2: PptTemplate[] = [
  deck({
    slug: "circular-fashion-business-plan", name: "Free Circular Fashion Business Plan PowerPoint Template", shortName: "Circular Fashion Business Plan", category: "Business Plan", categorySlug: "business-plan",
    description: "An editable circular-fashion business plan for explaining the customer need, material loop, offer, market entry, unit economics, operations, and funding gates.",
    longDescription: "This free circular fashion business plan PowerPoint template turns a sustainability idea into a decision-ready operating story. Eight editable slides cover the customer tension, material loop, offer, reachable market, unit economics, operations, evidence gates, and next decision. Its original material-passport system uses sage, indigo, clay, circular flow stamps, batch labels, and traceability rails built only from native PowerPoint shapes. It does not reuse reference illustrations, clothing graphics, text, charts, fonts, decorative elements, or layouts.",
    accent: "C65F42", dark: "243C35", soft: "E6EAD8", tags: ["Circular fashion", "Business plan", "Sustainable business", "16:9"],
    cover: ["CIRCULAR FASHION · 2027", "Build value into every return loop", "A business plan connecting customer demand, material recovery, margins, and operating proof."],
    story: [
      ["01 · TENSION", "Closets hold value that the current system loses", "Define the customer moment, current compromise, disposal friction, trust barrier, and urgency.", "4 gaps"],
      ["02 · LOOP", "Every item carries a visible route back", "Map intake, grading, renewal, resale, repair, recycling, and the data handed between stages."],
      ["03 · OFFER", "One promise connects style, condition, and traceability", "Explain the assortment, quality standard, service experience, return incentive, and proof."],
      ["04 · ENTRY", "Start where supply density meets repeat demand", "Separate the total market from a reachable launch community, acquisition route, and expansion trigger.", "12K buyers"],
      ["05 · ECONOMICS", "Margin depends on recovery yield—not volume alone", "Show illustrative purchase cost, processing, yield, price, returns, and sensitivity assumptions."],
      ["06 · OPERATIONS", "Batch-level decisions protect speed and quality", "Assign intake criteria, routing rules, capacity, ownership, quality checks, and exception handling."],
      ["07 · GATE", "Fund the next loop only after demand and yield hold", "Close with the illustrative capital need, validation period, thresholds, milestones, and owner.", "$240K"],
    ],
    included: ["Plan cover", "Customer tension", "Circular material loop", "Product offer", "Market entry", "Unit economics", "Operating model", "Funding gate"],
    bestFor: ["Circular-fashion startups", "Resale businesses", "Sustainability ventures", "Investor planning"],
  }),
  deck({
    slug: "fintech-control-room-pitch-deck", name: "Free FinTech Startup Pitch Deck PowerPoint Template", shortName: "FinTech Control Room Pitch Deck", category: "Startup Pitch Deck", categorySlug: "pitch-deck",
    description: "A fintech pitch deck for presenting a costly money workflow, product rails, trust controls, traction, market entry, economics, moat, and funding ask.",
    longDescription: "This free FinTech startup pitch deck PowerPoint template makes a financial workflow legible to investors without relying on stock graphics. Eight editable slides cover the problem, transaction rails, trust model, traction, beachhead market, unit economics, defensibility, and ask. Its original control-room design combines near-black navy, electric blue, copper, ledger rows, status lamps, and reconciliation panels made from editable native shapes. No reference imagery, gradients, icons, charts, fonts, wording, or recognizable composition is reproduced.",
    accent: "4FA7FF", dark: "101C2E", soft: "DCE9F2", tags: ["FinTech", "Startup pitch deck", "Fundraising", "16:9"],
    cover: ["FINTECH · SEED ROUND", "Make every money movement explainable", "A control-room pitch for faster settlement, visible risk, and trustworthy operations."],
    story: [
      ["01 · FRICTION", "Finance teams reconcile the same truth more than once", "Show the fragmented workflow, delay, affected operator, failure cost, and switching trigger.", "17 hrs"],
      ["02 · RAILS", "One ledger connects request, approval, movement, and proof", "Trace capture, policy, execution, settlement, reconciliation, exception, and audit ownership."],
      ["03 · TRUST", "Controls travel with the transaction", "Explain permissions, limits, verification, monitoring, human review, rollback, and evidence retention."],
      ["04 · TRACTION", "Repeated use is the strongest early signal", "Report illustrative activation, weekly use, retained cohorts, processed volume, and qualification limits.", "$8.4M"],
      ["05 · BEACHHEAD", "Enter through teams where reconciliation blocks growth", "Define the first buyer, reachable accounts, buying event, integration surface, and adjacent expansion."],
      ["06 · ECONOMICS", "Usage revenue grows with verified customer value", "Connect pricing, gross margin, support load, acquisition assumptions, retention, and payback."],
      ["07 · ASK", "Raise to prove repeatable deployment and distribution", "State the illustrative ask, runway, hiring, product, compliance, revenue, and evidence milestones.", "$2.6M"],
    ],
    included: ["Pitch cover", "Customer friction", "Product rails", "Trust controls", "Traction", "Beachhead market", "Unit economics", "Funding ask"],
    bestFor: ["FinTech founders", "Payments startups", "Finance automation", "Seed fundraising"],
  }),
  deck({
    slug: "structural-grid-company-profile", name: "Free Construction Company Profile PowerPoint Template", shortName: "Structural Grid Company Profile", category: "Company Profile", categorySlug: "company-profile",
    description: "A construction company profile for presenting credentials, services, delivery controls, selected proof, safety culture, team, capacity, and project fit.",
    longDescription: "This free construction company profile PowerPoint template gives engineering and building firms a precise, credible introduction. Eight editable slides cover credentials, client need, services, delivery system, selected proof, safety and quality, responsible team, and project fit. Its original structural-grid visual system uses concrete gray, safety yellow, steel blue, beam lines, inspection marks, and dimension notation created from PowerPoint-native shapes. It excludes all source photographs, architecture imagery, violet styling, fonts, icons, words, and layouts.",
    accent: "F4C542", dark: "26313A", soft: "E4E8E8", tags: ["Construction company", "Company profile", "Engineering", "16:9"],
    cover: ["COMPANY PROFILE · 2027", "Built around accountable handoffs", "Credentials, controls, capacity, and selected proof for complex construction programs."],
    story: [
      ["01 · CREDENTIALS", "Experience is useful when it matches the project risk", "Present verified years, disciplines, regions, capacity, certifications, and delivery responsibility.", "18 yrs"],
      ["02 · NEED", "Clients need certainty across changing site conditions", "Define schedule, coordination, access, quality, cost, safety, and communication pressures."],
      ["03 · SERVICES", "Services align to the structure of delivery", "Group preconstruction, civil, structural, systems, closeout, and maintenance by outcome."],
      ["04 · CONTROLS", "Field evidence moves through one review grid", "Show planning, permits, inspection, change, cost, schedule, reporting, and escalation ownership."],
      ["05 · PROOF", "Selected projects make capability specific", "Use placeholder scope, role, constraint, response, measured result, period, and limitations.", "3 projects"],
      ["06 · CULTURE", "Safety and quality are leading operating signals", "Name observation, stop-work, inspection, learning, supplier, and corrective-action routines."],
      ["07 · FIT", "Start with the package where control matters most", "Close with project types, geographic fit, availability, procurement route, contact, and next review.", "Q1 slot"],
    ],
    included: ["Profile cover", "Credentials", "Client need", "Services", "Delivery controls", "Selected projects", "Safety and quality", "Project fit"],
    bestFor: ["Construction firms", "Civil engineering teams", "Contractor credentials", "Client introductions"],
  }),
  deck({
    slug: "digital-channel-launch-plan", name: "Free Digital Marketing Launch Plan PowerPoint Template", shortName: "Digital Channel Launch Plan", category: "Marketing Plan", categorySlug: "marketing",
    description: "A digital marketing launch plan for aligning the audience signal, promise, channel roles, content episodes, test budget, conversion path, and learning agenda.",
    longDescription: "This free digital marketing launch plan PowerPoint template turns disconnected content into a measurable channel story. Eight editable slides cover the launch objective, audience signal, message, channel roles, content sequence, experiment budget, conversion path, and review. Its original broadcast-board system uses bright white, ultramarine, magenta, signal green, frame counters, waveform bars, and episode cards made from native shapes. It does not use source icons, charts, stars, backgrounds, gradients, fonts, copy, or layouts.",
    accent: "5B4DFF", dark: "20213A", soft: "E5F5EC", tags: ["Digital marketing", "Launch plan", "Channel strategy", "16:9"],
    cover: ["DIGITAL LAUNCH · 8 WEEKS", "Turn one useful promise into a repeatable signal", "An episode-led plan connecting channels, content, conversion, budget, and learning."],
    story: [
      ["01 · OUTCOME", "Name the customer behavior the launch must create", "Connect the commercial objective to one observable action, time horizon, and guardrail.", "+20%"],
      ["02 · SIGNAL", "Design for the moment attention becomes intent", "Describe the audience context, trigger, competing choice, trusted proof, and unanswered question."],
      ["03 · MESSAGE", "One promise should survive every channel format", "Build the claim, reason to believe, evidence, objection response, and next action."],
      ["04 · CHANNELS", "Assign channels by job—not habit", "Separate discovery, validation, capture, conversion, onboarding, and advocacy responsibilities.", "6 roles"],
      ["05 · EPISODES", "Sequence content from tension to demonstrated value", "Plan eight original episodes with a question, proof format, owner, CTA, and reuse rule."],
      ["06 · TESTS", "Fund learning before scaling reach", "Allocate placeholder spend by hypothesis, audience, creative, threshold, stop rule, and next decision."],
      ["07 · REVIEW", "Read the whole path before calling a winner", "Review reach quality, engaged visits, qualified starts, completion, cost, retention, and action.", "$36 CPA"],
    ],
    included: ["Launch cover", "Marketing outcome", "Audience signal", "Message system", "Channel roles", "Content episodes", "Test budget", "Conversion review"],
    bestFor: ["Product launches", "Digital campaigns", "Content marketing", "Growth experiments"],
  }),
  deck({
    slug: "engineering-systems-project-proposal", name: "Free Engineering Systems Project Proposal PowerPoint Template", shortName: "Engineering Systems Proposal", category: "Project Proposal", categorySlug: "project-proposal",
    description: "An engineering project proposal for defining the constraint, target state, system boundaries, work packages, validation, schedule, risk controls, and approval gate.",
    longDescription: "This free engineering systems project proposal PowerPoint template frames a technical initiative around evidence and accountable decisions. Eight editable slides cover the current constraint, target state, system boundary, work packages, validation method, schedule, risk controls, and approval. Its original technical-console visual language combines graphite, frost, solar orange, mint, coordinate axes, test vectors, and equipment-status cells using only editable native shapes. It does not copy reference geometry, black gradient treatment, icons, type, text, or page sequence.",
    accent: "FF7043", dark: "182126", soft: "DDE9E5", tags: ["Engineering proposal", "Project proposal", "Systems design", "16:9"],
    cover: ["ENGINEERING PROPOSAL · GATE 01", "Prove the system before scaling the asset", "A bounded proposal for requirements, work packages, tests, risks, schedule, and approval."],
    story: [
      ["01 · CONSTRAINT", "The present system fails under peak conditions", "Quantify the placeholder load, bottleneck, affected operations, failure cost, and urgency.", "72% load"],
      ["02 · TARGET", "Success is a measurable operating envelope", "Define throughput, quality, reliability, safety, maintainability, cost, and acceptance thresholds."],
      ["03 · BOUNDARY", "Interfaces determine where risk changes hands", "Map inputs, outputs, upstream and downstream owners, exclusions, assumptions, and dependencies."],
      ["04 · PACKAGES", "Work packages finish at verifiable handoffs", "Sequence requirements, design, prototype, integration, commissioning, training, and closeout.", "7 packages"],
      ["05 · VALIDATE", "Tests connect requirements to observed evidence", "State method, environment, sample, instrumentation, pass criteria, exception path, and owner."],
      ["06 · CONTROLS", "Risks remain visible at every evidence gate", "Track safety, scope, interface, supplier, schedule, cost, performance, and change controls."],
      ["07 · APPROVAL", "Authorize design against explicit conditions", "Close with the illustrative budget, schedule, decision owner, conditions, and immediate next step.", "$680K"],
    ],
    included: ["Proposal cover", "System constraint", "Target state", "System boundary", "Work packages", "Validation plan", "Risk controls", "Approval gate"],
    bestFor: ["Engineering proposals", "Systems implementations", "Capital projects", "Technical approvals"],
  }),
  deck({
    slug: "quarterly-sales-review-presentation", name: "Free Quarterly Sales Review PowerPoint Template", shortName: "Quarterly Sales Review", category: "Sales Report", categorySlug: "sales-report",
    description: "A quarterly sales review for explaining revenue movement, target gaps, pipeline quality, segment performance, account signals, forecast confidence, and next-quarter actions.",
    longDescription: "This free quarterly sales review PowerPoint template helps leaders move from headline numbers to owned actions. Eight editable slides cover the executive readout, revenue bridge, target gaps, pipeline quality, segment movement, account evidence, forecast confidence, and next-quarter priorities. Its original receipt-roll visual system uses carbon, paper white, bright yellow, red audit marks, SKU-like labels, and continuous ledger strips built from native PowerPoint shapes. No source yellow theme, charts, tables, icons, sample data, text, or slide arrangements are reused.",
    accent: "F3CF3D", dark: "222424", soft: "F0EEE3", tags: ["Quarterly sales review", "Sales report", "Revenue", "16:9"],
    cover: ["SALES REVIEW · Q4 2026", "Read the quarter like one continuous receipt", "Revenue movement, pipeline quality, account proof, forecast confidence, and owned actions."],
    story: [
      ["01 · READOUT", "The quarter landed above plan with a mix warning", "Compare illustrative bookings, target, prior period, margin, new business, expansion, and churn.", "104%"],
      ["02 · BRIDGE", "Expansion offset two delayed enterprise decisions", "Reconcile opening plan, created, won, expanded, contracted, churned, slipped, and closing result."],
      ["03 · TARGETS", "Performance gaps have different operating causes", "Separate volume, conversion, size, cycle, retention, and capacity instead of averaging variance."],
      ["04 · PIPELINE", "Coverage is sufficient; verified next actions are not", "Show stage, age, conversion, concentration, customer evidence, and risk-adjusted coverage.", "3.2×"],
      ["05 · SEGMENTS", "Mid-market speed leads while enterprise value builds", "Compare segments using consistent placeholder revenue, cycle, conversion, expansion, and risk measures."],
      ["06 · FORECAST", "Confidence improves when assumptions are visible", "Present commit, upside, downside, close events, dependencies, owners, and update cadence."],
      ["07 · ACTIONS", "Convert the review into five owned moves", "Assign customer action, owner, support, due date, evidence signal, and next-quarter decision.", "5 owners"],
    ],
    included: ["Review cover", "Executive readout", "Revenue bridge", "Target gaps", "Pipeline health", "Segment performance", "Forecast confidence", "Owned actions"],
    bestFor: ["Quarterly business reviews", "Sales leadership", "Revenue operations", "Board updates"],
  }),
  deck({
    slug: "constellation-lesson-plan-presentation", name: "Free Constellation Lesson Plan PowerPoint Template", shortName: "Constellation Lesson Plan", category: "Lesson Plan", categorySlug: "education",
    description: "An astronomy lesson plan for guiding learners through observation, pattern recognition, sky coordinates, cultural interpretation, practice, assessment, and reflection.",
    longDescription: "This free constellation lesson plan PowerPoint template provides an inquiry-led classroom sequence without using external imagery. Eight editable slides cover the learning goal, observation prompt, star-pattern concept, coordinate model, cultural perspective, guided practice, exit check, and extension. Its original observatory-dial design combines midnight blue, chalk white, amber, aqua, orbit rings, sighting ticks, and coordinate cards made from native PowerPoint shapes. It excludes source stars, illustrations, maps, fonts, text, gold palette placement, and page layouts.",
    accent: "F2B84B", dark: "17243C", soft: "DCECF0", tags: ["Astronomy lesson", "Lesson plan", "Constellations", "16:9"],
    cover: ["SCIENCE LESSON · 50 MIN", "Read the night sky as evidence and story", "An inquiry sequence for observing patterns, using coordinates, comparing interpretations, and explaining claims."],
    story: [
      ["01 · TARGET", "Observe, map, compare, and justify a sky pattern", "Translate the goal into learner-friendly success criteria, vocabulary, evidence, and accessibility.", "4 goals"],
      ["02 · NOTICE", "Begin with points before naming a constellation", "Invite learners to mark, group, rotate, compare, question, and explain an initial pattern."],
      ["03 · MODEL", "A pattern changes with viewpoint and convention", "Use editable points and sight lines to distinguish observation, coordinate, label, and interpretation."],
      ["04 · LOCATE", "Coordinates make observations repeatable", "Model horizon, direction, altitude, time, recording, uncertainty, and a safe observation routine.", "6 fields"],
      ["05 · PERSPECTIVE", "Communities connect the same stars differently", "Compare interpretations respectfully while separating cultural story from astronomical measurement."],
      ["06 · PRACTICE", "Build and defend one original pattern", "Pairs map a set of points, name a relationship, cite evidence, exchange maps, and revise."],
      ["07 · EXIT", "Check observation, mapping, and reasoning separately", "Collect one coordinate, one pattern claim, one supporting observation, and the next question.", "3 checks"],
    ],
    included: ["Lesson cover", "Learning target", "Observation prompt", "Pattern model", "Sky coordinates", "Cultural perspective", "Guided practice", "Exit ticket"],
    bestFor: ["Elementary science", "Astronomy lessons", "Inquiry learning", "Classroom observation"],
  }),
  deck({
    slug: "evidence-coding-thesis-defense", name: "Free Qualitative Research Thesis Defense PowerPoint Template", shortName: "Evidence Coding Thesis Defense", category: "Thesis Defense", categorySlug: "thesis-defense",
    description: "A qualitative thesis defense for presenting the research question, literature gap, sampling, coding method, evidence themes, interpretation, limitations, and contribution.",
    longDescription: "This free qualitative research thesis defense PowerPoint template makes the chain from transcript to claim explicit. Eight editable slides cover the question, literature gap, sample, coding method, evidence themes, interpretation, limitations, and contribution. Its original evidence-coding visual system uses warm white, ink, cobalt, vermilion, transcript margins, code tabs, memo cards, and claim-evidence links created from native shapes. It does not reuse source laboratory imagery, icons, charts, fonts, wording, colors, or page structure.",
    accent: "315CB5", dark: "242427", soft: "F0E9DC", tags: ["Qualitative research", "Thesis defense", "Academic presentation", "16:9"],
    cover: ["THESIS DEFENSE · 2027", "Trace every claim back to its evidence", "A qualitative defense organized around question, sample, coding, themes, limits, and contribution."],
    story: [
      ["01 · QUESTION", "The study asks how participants make one bounded decision", "Define the phenomenon, participants, context, period, perspective, and claim boundary.", "1 question"],
      ["02 · GAP", "Prior work describes outcomes more often than meaning-making", "Synthesize agreement, tension, missing context, methodological gap, and research opportunity."],
      ["03 · SAMPLE", "Purposeful selection matches the research question", "State illustrative recruitment, inclusion, diversity, setting, saturation logic, ethics, and limits.", "n=24"],
      ["04 · CODING", "Codes evolve through comparison, memoing, and challenge", "Show familiarization, open codes, codebook, double coding, negative cases, themes, and audit trail."],
      ["05 · THEMES", "Three themes explain a shared decision pattern", "Present each placeholder theme with evidence type, variation, counterexample, context, and confidence."],
      ["06 · INTERPRET", "The mechanism is plausible within a narrow setting", "Separate participant account, analytic inference, theory connection, alternative reading, and uncertainty."],
      ["07 · CONTRIBUTION", "The contribution is a transparent explanatory model", "Close with theory, practice, transferability, limitations, reflexivity, open questions, and next study.", "3 claims"],
    ],
    included: ["Defense cover", "Research question", "Literature gap", "Sample", "Coding method", "Evidence themes", "Interpretation", "Contribution and limits"],
    bestFor: ["Qualitative theses", "Interview studies", "Social research", "Dissertation defenses"],
  }),
  deck({
    slug: "clinical-decision-board-case", name: "Free Clinical Decision Board Case PowerPoint Template", shortName: "Clinical Decision Board Case", category: "Clinical Case", categorySlug: "medical",
    description: "A de-identified clinical case template for presenting the concern, history, findings, differential, decision path, response, safety review, and learning points.",
    longDescription: "This free clinical decision board PowerPoint template supports a careful, de-identified case discussion. Eight editable slides cover the presenting concern, focused history, relevant findings, differential, decision path, observed response, safety review, and learning points. Its original diagnostic-board design uses off-white, deep teal, coral, lavender, evidence columns, uncertainty chips, and decision matrices built from native PowerPoint shapes. All content is fictional placeholder material for education only; no source medical illustrations, claims, icons, text, charts, or layouts are used.",
    accent: "E66658", dark: "193E43", soft: "E8E3F0", tags: ["Clinical case", "Medical education", "Case conference", "16:9"],
    cover: ["CLINICAL CASE · EDUCATION ONLY", "Make the reasoning visible before the conclusion", "A de-identified placeholder case organized by evidence, uncertainty, decisions, response, and learning."],
    story: [
      ["01 · CONCERN", "Begin with the change that prompted evaluation", "Summarize fictional onset, trajectory, severity, context, affected function, and meaningful negatives.", "Day 0"],
      ["02 · HISTORY", "Focus history on facts that change probability", "Organize de-identified context, relevant history, exposures, medication, preferences, and red flags."],
      ["03 · FINDINGS", "Separate observations from interpretations", "Present placeholder examination, measurements, tests, missing information, reliability, and limitations.", "5 findings"],
      ["04 · DIFFERENTIAL", "Compare explanations against the same evidence", "Use an editable matrix for supporting, conflicting, absent, uncertain, and safety-critical evidence."],
      ["05 · DECISION", "Choose the next step with uncertainty intact", "Show options, anticipated benefit, risk, reversibility, patient preference, monitoring, and escalation."],
      ["06 · RESPONSE", "Observed change does not prove a single cause", "Compare fictional baseline and follow-up, adherence, context, variation, adverse signals, and uncertainty."],
      ["07 · LEARNING", "Close with transferable reasoning and explicit limits", "State safety points, follow-up, case limitations, unresolved questions, and teaching takeaways.", "3 lessons"],
    ],
    included: ["Case cover", "Presenting concern", "Focused history", "Relevant findings", "Differential matrix", "Decision path", "Observed response", "Learning points"],
    bestFor: ["Case conferences", "Medical education", "Clinical reasoning", "De-identified reviews"],
  }),
  deck({
    slug: "cyber-resilience-technology-brief", name: "Free Cyber Resilience Technology PowerPoint Template", shortName: "Cyber Resilience Brief", category: "AI & Technology", categorySlug: "artificial-intelligence",
    description: "A cyber resilience technology brief for explaining the threat model, critical assets, attack paths, controls, detection evidence, response workflow, recovery, and investment priorities.",
    longDescription: "This free cyber resilience PowerPoint template frames security as an operating system rather than a collection of icons. Eight editable slides cover the mandate, threat model, critical assets, attack paths, preventive controls, detection evidence, response and recovery, and investment priorities. Its original checksum-console design combines black, terminal green, icy blue, warning amber, log rows, hash blocks, and integrity stamps made from native PowerPoint shapes. It excludes all source hacker illustrations, photographs, icons, gradients, text, fonts, and slide compositions.",
    accent: "65E59B", dark: "101615", soft: "DCEDE7", tags: ["Cybersecurity", "Technology", "Risk management", "16:9"],
    cover: ["CYBER RESILIENCE · BRIEF 01", "Design for continuity—not perfect prevention", "A technology brief connecting threats, assets, controls, detection, response, recovery, and investment."],
    story: [
      ["01 · MANDATE", "Protect the services the organization must keep delivering", "Define critical outcomes, authority, risk appetite, obligations, operating assumptions, and measures.", "4 services"],
      ["02 · THREATS", "Threat models connect capability to plausible paths", "Describe actors, objectives, entry points, prerequisites, affected assets, impact, and uncertainty."],
      ["03 · ASSETS", "Criticality depends on the service—not the inventory label", "Map data, identity, endpoints, applications, infrastructure, suppliers, owners, and recovery needs."],
      ["04 · PATHS", "Controls are strongest when arranged across the path", "Trace access, execution, persistence, privilege, movement, action, detection, and containment.", "8 stages"],
      ["05 · SIGNALS", "Detection needs evidence, thresholds, and an owner", "Connect logs, identity, endpoint, network, application, human reports, confidence, and action."],
      ["06 · RESPONSE", "Practice the decisions that preserve continuity", "Sequence triage, contain, communicate, investigate, recover, validate, learn, and update controls."],
      ["07 · PRIORITIES", "Invest where risk reduction and readiness meet", "Rank placeholder initiatives by service impact, evidence gap, feasibility, dependency, and review date.", "90 days"],
    ],
    included: ["Technology cover", "Security mandate", "Threat model", "Critical assets", "Attack paths", "Detection signals", "Response and recovery", "Investment priorities"],
    bestFor: ["Cybersecurity strategy", "Technology leadership", "Risk committees", "Security training"],
  }),
  deck({
    slug: "fashion-pattern-portfolio", name: "Free Fashion Design Portfolio PowerPoint Template", shortName: "Fashion Pattern Portfolio", category: "Creative Portfolio", categorySlug: "portfolio",
    description: "A fashion design portfolio for presenting a point of view, collection edit, concept development, pattern process, materials, fittings, outcomes, and contact.",
    longDescription: "This free fashion design portfolio PowerPoint template gives a collection an editorial but highly editable frame. Eight slides cover the creative point of view, collection edit, concept, pattern development, materials, fitting iteration, selected outcomes, and contact. Its original pattern-room system uses natural canvas, forest green, poppy red, cobalt, cut lines, seam allowance marks, swatch cards, and abstract garment blocks built entirely from native PowerPoint shapes. It does not reuse reference photographs, lookbook imagery, stickers, illustrations, fonts, copy, green placement, or page layouts.",
    accent: "E74D3C", dark: "214338", soft: "E8E0CE", tags: ["Fashion portfolio", "Creative portfolio", "Design process", "16:9"],
    cover: ["FASHION PORTFOLIO · 2027", "Shape, movement, and making in one collection", "Selected work tracing concept, pattern, material, fitting, outcome, and creative direction."],
    story: [
      ["01 · POSITION", "The work begins with movement before silhouette", "State the creative perspective, wearer, context, recurring questions, craft, and desired feeling.", "1 thesis"],
      ["02 · EDIT", "Curate the collection around contrast and progression", "Introduce placeholder looks through role, proportion, material, technique, color, and relationship."],
      ["03 · CONCEPT", "A clear tension guides each design decision", "Translate research into form principles without importing source imagery, graphics, or wording."],
      ["04 · PATTERN", "Cut lines reveal how the silhouette is built", "Show editable blocks for volume, balance, grain, seam, allowance, construction, and iteration.", "6 pieces"],
      ["05 · MATERIAL", "Material behavior changes the form", "Present original swatch placeholders for weight, drape, texture, sourcing, care, constraint, and choice."],
      ["06 · FITTING", "Each fitting resolves one visible question", "Sequence observation, hypothesis, pin, recut, test, compare, decide, and document."],
      ["07 · CONTACT", "Invite work that values concept and construction", "Close with roles, capabilities, preferred briefs, availability, location, contact, and next step.", "Q2"],
    ],
    included: ["Portfolio cover", "Creative position", "Collection edit", "Concept development", "Pattern process", "Material system", "Fitting iteration", "Contact"],
    bestFor: ["Fashion designers", "Design-school portfolios", "Collection reviews", "Creative interviews"],
  }),
  deck({
    slug: "dependency-calendar-product-roadmap", name: "Free Dependency Calendar Product Roadmap PowerPoint Template", shortName: "Dependency Calendar Roadmap", category: "Product Roadmap", categorySlug: "product-roadmap",
    description: "A product roadmap for aligning outcomes, evidence, calendar windows, dependency chains, decision gates, release criteria, measures, and the next review.",
    longDescription: "This free dependency calendar product roadmap PowerPoint template exposes what must happen before release dates become credible. Eight editable slides cover the outcome, evidence, roadmap windows, dependency chain, decision gates, release criteria, measures, and review. Its original calendar-domino design combines aubergine, coral, mint, cream, month tiles, vertical dependency pieces, confidence dots, and decision cards made from native PowerPoint shapes. It does not reproduce the reference template's roadmap graphics, animation, icons, charts, typography, wording, or page sequence.",
    accent: "FF6F61", dark: "2E1F3A", soft: "DDEEDF", tags: ["Product roadmap", "Dependencies", "Release planning", "16:9"],
    cover: ["PRODUCT ROADMAP · H2 2027", "Dates become useful when dependencies are visible", "A calendar roadmap connecting customer outcomes, evidence, handoffs, gates, criteria, and decisions."],
    story: [
      ["01 · OUTCOME", "The roadmap begins with a customer behavior", "Define the user, moment, changed action, quality, speed, business value, and guardrail.", "< 3 min"],
      ["02 · EVIDENCE", "Confidence grows through converging signals", "Combine behavior, research, support, commercial context, feasibility, reliability, and risk."],
      ["03 · WINDOWS", "Use calendar windows to express intent and uncertainty", "Organize current, committed, conditional, and exploratory work without false date precision."],
      ["04 · LINKS", "Every release sits on a chain of owned handoffs", "Map research, design, data, platform, policy, enablement, support, and launch dependencies.", "8 links"],
      ["05 · GATES", "Decisions happen when evidence clears a threshold", "Define discovery, design, build, evaluate, ready, release, expand, and retire gates."],
      ["06 · CRITERIA", "Release readiness is more than feature completion", "Check value, usability, quality, reliability, privacy, support, rollback, and communication."],
      ["07 · REVIEW", "Move dates only after revisiting the evidence", "Compare expected and observed signals, confidence, dependency movement, choices, owners, and next review.", "30 days"],
    ],
    included: ["Roadmap cover", "Customer outcome", "Evidence signals", "Calendar windows", "Dependency chain", "Decision gates", "Release criteria", "Review cadence"],
    bestFor: ["Product planning", "Cross-functional roadmaps", "Release governance", "Leadership reviews"],
  }),
];
