import type { Locale } from "@/lib/i18n";
import type { PptTemplate, TemplateCategory } from "@/lib/templates";

export type TemplateCopy = {
  nav: string; business: string; home: string;
  badge: string; title1: string; title2: string; lead: string;
  noSignup: string; editable: string; widescreen: string; freeUse: string;
  newFree: string; libraryTitle: string; libraryLead: string; browseBusiness: string;
  businessBadge: string; businessTitle1: string; businessTitle2: string; businessLead: string; choose: string;
  freeEditable: string; slides: string; preview: string; previewTitle: string; previewLead: string;
  about: string; aboutTitle: string; bestFor: string; details: string; format: string; ratio: string; language: string; fonts: string; license: string; readLicense: string;
  included: string; includedTitle: string; ready: string; readyLead: string; more: string; related: string;
  download: string; customize: string; terms: string; previous: string; next: string; close: string;
};

const en: TemplateCopy = {
  nav: "Templates", business: "Business", home: "Home", badge: "FREE POWERPOINT TEMPLATES", title1: "Start with a strong story.", title2: "Make it yours.", lead: "Download genuinely editable presentation templates, built for real business conversations—not just attractive thumbnails.",
  noSignup: "No sign-up", editable: "Editable PPTX", widescreen: "16:9 widescreen", freeUse: "Free to use", newFree: "NEW & FREE", libraryTitle: "Professional templates for your next presentation", libraryLead: "Every deck includes eight purposeful layouts, editable native PowerPoint elements, and clear placeholder content.", browseBusiness: "Browse business templates",
  businessBadge: "BUSINESS TEMPLATES", businessTitle1: "Free business", businessTitle2: "PowerPoint templates", businessLead: "Editable presentation structures for planning, pitching, selling, and introducing your company with clarity.", choose: "Choose a business presentation template",
  freeEditable: "FREE · EDITABLE · 16:9", slides: "8 slides · PPTX", preview: "Preview template", previewTitle: "Eight layouts included", previewLead: "Click any slide to inspect it at a larger size.", about: "ABOUT THIS TEMPLATE", aboutTitle: "A practical structure you can make your own", bestFor: "Best for", details: "Template details", format: "Format", ratio: "Ratio", language: "Language", fonts: "Fonts", license: "License", readLicense: "Read template license", included: "WHAT'S INCLUDED", includedTitle: "A complete eight-slide story", ready: "Ready to build your presentation?", readyLead: "Download the editable file now, or use AI to adapt the structure to your content.", more: "MORE FREE TEMPLATES", related: "Related business presentation templates", download: "Download free PPTX", customize: "Customize with AI", terms: "No sign-up · Editable slides · Free personal & commercial use", previous: "Previous", next: "Next", close: "Close preview",
};

const copies: Record<Locale, TemplateCopy> = {
  en,
  "zh-CN": { ...en, nav:"模板",business:"商务",home:"首页",badge:"免费 POWERPOINT 模板",title1:"从清晰的故事开始。",title2:"打造你的专属演示。",lead:"免费下载真正可编辑的演示模板，专为真实商务沟通设计，而不只是好看的缩略图。",noSignup:"无需注册",editable:"可编辑 PPTX",widescreen:"16:9 宽屏",freeUse:"免费使用",newFree:"全新 · 免费",libraryTitle:"为下一次演示选择专业模板",libraryLead:"每套模板包含 8 个实用版式、可编辑的 PowerPoint 原生元素和清晰的占位内容。",browseBusiness:"浏览商务模板",businessBadge:"商务模板",businessTitle1:"免费商务",businessTitle2:"PowerPoint 模板",businessLead:"适用于商业规划、路演、销售和公司介绍的可编辑演示结构。",choose:"选择商务演示模板",freeEditable:"免费 · 可编辑 · 16:9",slides:"8 页 · PPTX",preview:"预览模板",previewTitle:"包含 8 个版式",previewLead:"点击任意幻灯片查看大图。",about:"关于此模板",aboutTitle:"实用结构，自由定制",bestFor:"适用场景",details:"模板详情",format:"格式",ratio:"比例",language:"语言",fonts:"字体",license:"许可",readLicense:"查看模板许可",included:"包含内容",includedTitle:"完整的 8 页叙事结构",ready:"准备制作演示了吗？",readyLead:"立即下载可编辑文件，或使用 AI 根据你的内容调整结构。",more:"更多免费模板",related:"相关商务演示模板",download:"免费下载 PPTX",customize:"使用 AI 定制",terms:"无需注册 · 幻灯片可编辑 · 个人和商业用途免费",previous:"上一页",next:"下一页",close:"关闭预览" },
  "zh-TW": { ...en, nav:"範本",business:"商務",home:"首頁",badge:"免費 POWERPOINT 範本",title1:"從清晰的故事開始。",title2:"打造你的專屬簡報。",lead:"免費下載真正可編輯的簡報範本，專為真實商務溝通設計。",noSignup:"無需註冊",editable:"可編輯 PPTX",widescreen:"16:9 寬螢幕",freeUse:"免費使用",newFree:"全新 · 免費",libraryTitle:"為下一次簡報選擇專業範本",libraryLead:"每套範本包含 8 個實用版面、可編輯元素和清晰的預留內容。",browseBusiness:"瀏覽商務範本",businessBadge:"商務範本",businessTitle1:"免費商務",businessTitle2:"PowerPoint 範本",businessLead:"適用於商業規劃、提案、銷售和公司介紹的可編輯簡報結構。",choose:"選擇商務簡報範本",freeEditable:"免費 · 可編輯 · 16:9",slides:"8 頁 · PPTX",preview:"預覽範本",previewTitle:"包含 8 個版面",previewLead:"點擊任一投影片查看大圖。",about:"關於此範本",aboutTitle:"實用結構，自由調整",bestFor:"適用情境",details:"範本詳情",format:"格式",ratio:"比例",language:"語言",fonts:"字型",license:"授權",readLicense:"查看範本授權",included:"包含內容",includedTitle:"完整的 8 頁敘事結構",ready:"準備製作簡報了嗎？",readyLead:"立即下載可編輯檔案，或使用 AI 調整內容。",more:"更多免費範本",related:"相關商務簡報範本",download:"免費下載 PPTX",customize:"使用 AI 自訂",terms:"無需註冊 · 投影片可編輯 · 個人與商業用途免費",previous:"上一頁",next:"下一頁",close:"關閉預覽" },
  ja: { ...en, nav:"テンプレート",business:"ビジネス",home:"ホーム",badge:"無料 POWERPOINT テンプレート",title1:"強いストーリーから始めよう。",title2:"自分らしく仕上げよう。",lead:"実際のビジネスに使える、完全編集可能なプレゼンテーションテンプレートを無料でダウンロードできます。",noSignup:"登録不要",editable:"編集可能な PPTX",widescreen:"16:9 ワイド",freeUse:"無料で利用可能",newFree:"新着 · 無料",libraryTitle:"次のプレゼンに使えるプロ向けテンプレート",libraryLead:"各デッキには、8種類の実用的なレイアウトと編集可能なPowerPoint要素が含まれます。",browseBusiness:"ビジネステンプレートを見る",businessBadge:"ビジネステンプレート",businessTitle1:"無料ビジネス",businessTitle2:"PowerPoint テンプレート",businessLead:"企画、ピッチ、営業、会社紹介に使える編集可能な構成です。",choose:"ビジネステンプレートを選ぶ",freeEditable:"無料 · 編集可能 · 16:9",slides:"8枚 · PPTX",preview:"テンプレートを確認",previewTitle:"8種類のレイアウト",previewLead:"スライドをクリックして拡大表示できます。",about:"このテンプレートについて",aboutTitle:"自由に調整できる実用的な構成",bestFor:"おすすめ用途",details:"テンプレート詳細",format:"形式",ratio:"比率",language:"言語",fonts:"フォント",license:"ライセンス",readLicense:"ライセンスを確認",included:"収録内容",includedTitle:"8枚で構成されたストーリー",ready:"プレゼンを作成しますか？",readyLead:"編集可能なファイルをダウンロードするか、AIで内容に合わせて調整できます。",more:"その他の無料テンプレート",related:"関連するビジネステンプレート",download:"無料 PPTX をダウンロード",customize:"AIでカスタマイズ",terms:"登録不要 · 編集可能 · 個人・商用利用無料",previous:"前へ",next:"次へ",close:"プレビューを閉じる" },
  ko: { ...en, nav:"템플릿",business:"비즈니스",home:"홈",badge:"무료 POWERPOINT 템플릿",title1:"탄탄한 이야기로 시작하세요.",title2:"나만의 발표로 완성하세요.",lead:"실제 비즈니스 대화를 위해 설계된 완전 편집 가능한 프레젠테이션 템플릿을 무료로 받으세요.",noSignup:"가입 불필요",editable:"편집 가능한 PPTX",widescreen:"16:9 와이드",freeUse:"무료 사용",newFree:"신규 · 무료",libraryTitle:"다음 발표를 위한 전문 템플릿",libraryLead:"각 자료에는 8개의 실용적인 레이아웃과 편집 가능한 PowerPoint 요소가 포함됩니다.",browseBusiness:"비즈니스 템플릿 보기",businessBadge:"비즈니스 템플릿",businessTitle1:"무료 비즈니스",businessTitle2:"PowerPoint 템플릿",businessLead:"기획, 피칭, 영업 및 회사 소개를 위한 편집 가능한 구조입니다.",choose:"비즈니스 발표 템플릿 선택",freeEditable:"무료 · 편집 가능 · 16:9",slides:"8장 · PPTX",preview:"템플릿 미리보기",previewTitle:"8개 레이아웃 포함",previewLead:"슬라이드를 클릭해 크게 확인하세요.",about:"템플릿 소개",aboutTitle:"자유롭게 수정하는 실용적인 구조",bestFor:"추천 용도",details:"템플릿 정보",format:"형식",ratio:"비율",language:"언어",fonts:"글꼴",license:"라이선스",readLicense:"라이선스 보기",included:"포함 내용",includedTitle:"8장으로 완성되는 이야기",ready:"발표를 만들 준비가 되셨나요?",readyLead:"편집 가능한 파일을 받거나 AI로 내용에 맞게 수정하세요.",more:"더 많은 무료 템플릿",related:"관련 비즈니스 발표 템플릿",download:"무료 PPTX 다운로드",customize:"AI로 맞춤 설정",terms:"가입 불필요 · 편집 가능 · 개인 및 상업용 무료",previous:"이전",next:"다음",close:"미리보기 닫기" },
  fr: { ...en, nav:"Modèles",business:"Entreprise",home:"Accueil",badge:"MODÈLES POWERPOINT GRATUITS",title1:"Commencez par une histoire forte.",title2:"Personnalisez-la.",lead:"Téléchargez des modèles réellement modifiables, conçus pour de vraies présentations professionnelles.",noSignup:"Sans inscription",editable:"PPTX modifiable",widescreen:"Format 16:9",freeUse:"Utilisation gratuite",newFree:"NOUVEAU · GRATUIT",libraryTitle:"Des modèles professionnels pour votre prochaine présentation",libraryLead:"Chaque présentation contient huit mises en page utiles et des éléments PowerPoint modifiables.",browseBusiness:"Voir les modèles professionnels",businessBadge:"MODÈLES PROFESSIONNELS",businessTitle1:"Modèles PowerPoint",businessTitle2:"professionnels gratuits",businessLead:"Des structures modifiables pour planifier, convaincre, vendre et présenter votre entreprise.",choose:"Choisissez un modèle professionnel",freeEditable:"GRATUIT · MODIFIABLE · 16:9",slides:"8 diapositives · PPTX",preview:"Aperçu du modèle",previewTitle:"Huit mises en page incluses",previewLead:"Cliquez sur une diapositive pour l’agrandir.",about:"À PROPOS DU MODÈLE",aboutTitle:"Une structure pratique à personnaliser",bestFor:"Idéal pour",details:"Détails du modèle",format:"Format",ratio:"Ratio",language:"Langue",fonts:"Polices",license:"Licence",readLicense:"Lire la licence",included:"CONTENU INCLUS",includedTitle:"Une histoire complète en huit diapositives",ready:"Prêt à créer votre présentation ?",readyLead:"Téléchargez le fichier ou adaptez sa structure à votre contenu avec l’IA.",more:"AUTRES MODÈLES GRATUITS",related:"Modèles professionnels associés",download:"Télécharger le PPTX gratuit",customize:"Personnaliser avec l’IA",terms:"Sans inscription · Modifiable · Usage personnel et commercial gratuit",previous:"Précédent",next:"Suivant",close:"Fermer l’aperçu" },
  es: { ...en, nav:"Plantillas",business:"Negocios",home:"Inicio",badge:"PLANTILLAS POWERPOINT GRATIS",title1:"Empieza con una historia sólida.",title2:"Hazla tuya.",lead:"Descarga plantillas realmente editables, diseñadas para presentaciones profesionales reales.",noSignup:"Sin registro",editable:"PPTX editable",widescreen:"Pantalla 16:9",freeUse:"Uso gratuito",newFree:"NUEVO · GRATIS",libraryTitle:"Plantillas profesionales para tu próxima presentación",libraryLead:"Cada presentación incluye ocho diseños útiles y elementos nativos editables de PowerPoint.",browseBusiness:"Ver plantillas de negocios",businessBadge:"PLANTILLAS DE NEGOCIOS",businessTitle1:"Plantillas PowerPoint",businessTitle2:"de negocios gratis",businessLead:"Estructuras editables para planificar, presentar, vender y explicar tu empresa.",choose:"Elige una plantilla de negocios",freeEditable:"GRATIS · EDITABLE · 16:9",slides:"8 diapositivas · PPTX",preview:"Ver plantilla",previewTitle:"Ocho diseños incluidos",previewLead:"Haz clic en una diapositiva para ampliarla.",about:"SOBRE ESTA PLANTILLA",aboutTitle:"Una estructura práctica que puedes adaptar",bestFor:"Ideal para",details:"Detalles de la plantilla",format:"Formato",ratio:"Proporción",language:"Idioma",fonts:"Fuentes",license:"Licencia",readLicense:"Leer licencia",included:"QUÉ INCLUYE",includedTitle:"Una historia completa en ocho diapositivas",ready:"¿Listo para crear tu presentación?",readyLead:"Descarga el archivo editable o adapta su estructura con IA.",more:"MÁS PLANTILLAS GRATIS",related:"Plantillas de negocios relacionadas",download:"Descargar PPTX gratis",customize:"Personalizar con IA",terms:"Sin registro · Editable · Uso personal y comercial gratuito",previous:"Anterior",next:"Siguiente",close:"Cerrar vista previa" },
  ru: { ...en, nav:"Шаблоны",business:"Бизнес",home:"Главная",badge:"БЕСПЛАТНЫЕ ШАБЛОНЫ POWERPOINT",title1:"Начните с сильной истории.",title2:"Сделайте её своей.",lead:"Скачивайте редактируемые шаблоны, созданные для реальных деловых презентаций.",noSignup:"Без регистрации",editable:"Редактируемый PPTX",widescreen:"Формат 16:9",freeUse:"Бесплатно",newFree:"НОВОЕ · БЕСПЛАТНО",libraryTitle:"Профессиональные шаблоны для следующей презентации",libraryLead:"Каждый файл содержит восемь практичных макетов и редактируемые элементы PowerPoint.",browseBusiness:"Смотреть бизнес-шаблоны",businessBadge:"БИЗНЕС-ШАБЛОНЫ",businessTitle1:"Бесплатные бизнес-",businessTitle2:"шаблоны PowerPoint",businessLead:"Редактируемые структуры для планирования, питчей, продаж и представления компании.",choose:"Выберите бизнес-шаблон",freeEditable:"БЕСПЛАТНО · 16:9",slides:"8 слайдов · PPTX",preview:"Посмотреть шаблон",previewTitle:"Восемь макетов",previewLead:"Нажмите на слайд, чтобы увеличить его.",about:"О ШАБЛОНЕ",aboutTitle:"Практичная структура для ваших задач",bestFor:"Подходит для",details:"Параметры шаблона",format:"Формат",ratio:"Соотношение",language:"Язык",fonts:"Шрифты",license:"Лицензия",readLicense:"Открыть лицензию",included:"ЧТО ВКЛЮЧЕНО",includedTitle:"Полная история из восьми слайдов",ready:"Готовы создать презентацию?",readyLead:"Скачайте файл или адаптируйте структуру под свой материал с помощью ИИ.",more:"ЕЩЁ БЕСПЛАТНЫЕ ШАБЛОНЫ",related:"Похожие бизнес-шаблоны",download:"Скачать PPTX бесплатно",customize:"Настроить с ИИ",terms:"Без регистрации · Можно редактировать · Бесплатно для личного и коммерческого использования",previous:"Назад",next:"Далее",close:"Закрыть просмотр" },
};

export const templateCopy = (locale: Locale) => copies[locale];

const localizedNames: Partial<Record<Locale, Record<string, [string, string]>>> = {
  "zh-CN": {
    "business-plan-presentation":["免费商业计划 PowerPoint 模板","商业计划"], "startup-pitch-deck":["免费创业融资路演 PPT 模板","创业路演"], "company-profile-presentation":["免费公司介绍 PowerPoint 模板","公司介绍"],
    "marketing-plan-presentation":["免费营销计划 PowerPoint 模板","营销计划"], "project-proposal-presentation":["免费项目提案 PowerPoint 模板","项目提案"], "sales-report-presentation":["免费销售报告 PowerPoint 模板","销售报告"],
    "lesson-plan-presentation":["免费教学课件 PowerPoint 模板","教学课件"], "thesis-defense-presentation":["免费论文答辩 PowerPoint 模板","论文答辩"], "clinical-case-presentation":["免费医疗病例 PowerPoint 模板","医疗病例"],
    "artificial-intelligence-presentation":["免费人工智能 PowerPoint 模板","人工智能"], "creative-portfolio-presentation":["免费创意作品集 PowerPoint 模板","创意作品集"], "product-roadmap-presentation":["免费产品路线图 PowerPoint 模板","产品路线图"],
  },
  "zh-TW": {
    "business-plan-presentation":["免費商業計畫 PowerPoint 範本","商業計畫"], "startup-pitch-deck":["免費新創募資簡報範本","新創簡報"], "company-profile-presentation":["免費公司介紹 PowerPoint 範本","公司介紹"],
    "marketing-plan-presentation":["免費行銷計畫 PowerPoint 範本","行銷計畫"], "project-proposal-presentation":["免費專案提案 PowerPoint 範本","專案提案"], "sales-report-presentation":["免費銷售報告 PowerPoint 範本","銷售報告"],
    "lesson-plan-presentation":["免費教學課件 PowerPoint 範本","教學課件"], "thesis-defense-presentation":["免費論文答辯 PowerPoint 範本","論文答辯"], "clinical-case-presentation":["免費臨床病例 PowerPoint 範本","臨床病例"],
    "artificial-intelligence-presentation":["免費人工智慧 PowerPoint 範本","人工智慧"], "creative-portfolio-presentation":["免費創意作品集 PowerPoint 範本","創意作品集"], "product-roadmap-presentation":["免費產品路線圖 PowerPoint 範本","產品路線圖"],
  },
  ja: {
    "business-plan-presentation":["無料ビジネスプラン PowerPoint テンプレート","ビジネスプラン"], "startup-pitch-deck":["無料スタートアップ向けピッチ資料","スタートアップ・ピッチ"], "company-profile-presentation":["無料会社紹介 PowerPoint テンプレート","会社紹介"],
    "marketing-plan-presentation":["無料マーケティング計画 PowerPoint テンプレート","マーケティング計画"], "project-proposal-presentation":["無料プロジェクト提案 PowerPoint テンプレート","プロジェクト提案"], "sales-report-presentation":["無料営業レポート PowerPoint テンプレート","営業レポート"],
    "lesson-plan-presentation":["無料授業計画 PowerPoint テンプレート","授業計画"], "thesis-defense-presentation":["無料論文審査 PowerPoint テンプレート","論文審査"], "clinical-case-presentation":["無料臨床症例 PowerPoint テンプレート","臨床症例"],
    "artificial-intelligence-presentation":["無料 AI PowerPoint テンプレート","AI・テクノロジー"], "creative-portfolio-presentation":["無料クリエイティブポートフォリオ","ポートフォリオ"], "product-roadmap-presentation":["無料プロダクトロードマップ PowerPoint","製品ロードマップ"],
  },
  ko: {
    "business-plan-presentation":["무료 사업계획서 PowerPoint 템플릿","사업계획서"], "startup-pitch-deck":["무료 스타트업 피치덱 템플릿","스타트업 피치덱"], "company-profile-presentation":["무료 회사소개 PowerPoint 템플릿","회사소개"],
    "marketing-plan-presentation":["무료 마케팅 계획 PowerPoint 템플릿","마케팅 계획"], "project-proposal-presentation":["무료 프로젝트 제안 PowerPoint 템플릿","프로젝트 제안"], "sales-report-presentation":["무료 영업 보고서 PowerPoint 템플릿","영업 보고서"],
    "lesson-plan-presentation":["무료 수업 계획 PowerPoint 템플릿","수업 계획"], "thesis-defense-presentation":["무료 학위 논문 발표 PowerPoint 템플릿","논문 발표"], "clinical-case-presentation":["무료 임상 사례 PowerPoint 템플릿","임상 사례"],
    "artificial-intelligence-presentation":["무료 인공지능 PowerPoint 템플릿","인공지능"], "creative-portfolio-presentation":["무료 크리에이티브 포트폴리오 템플릿","포트폴리오"], "product-roadmap-presentation":["무료 제품 로드맵 PowerPoint 템플릿","제품 로드맵"],
  },
  fr: {
    "business-plan-presentation":["Modèle PowerPoint gratuit de business plan","Business plan"], "startup-pitch-deck":["Modèle gratuit de pitch deck startup","Pitch deck startup"], "company-profile-presentation":["Modèle PowerPoint gratuit de présentation d’entreprise","Présentation d’entreprise"],
    "marketing-plan-presentation":["Modèle PowerPoint gratuit de plan marketing","Plan marketing"], "project-proposal-presentation":["Modèle PowerPoint gratuit de proposition de projet","Proposition de projet"], "sales-report-presentation":["Modèle PowerPoint gratuit de rapport commercial","Rapport commercial"],
    "lesson-plan-presentation":["Modèle PowerPoint gratuit de plan de cours","Plan de cours"], "thesis-defense-presentation":["Modèle PowerPoint gratuit de soutenance","Soutenance de thèse"], "clinical-case-presentation":["Modèle PowerPoint gratuit de cas clinique","Cas clinique"],
    "artificial-intelligence-presentation":["Modèle PowerPoint gratuit sur l’intelligence artificielle","Intelligence artificielle"], "creative-portfolio-presentation":["Modèle PowerPoint gratuit de portfolio créatif","Portfolio créatif"], "product-roadmap-presentation":["Modèle PowerPoint gratuit de feuille de route produit","Feuille de route produit"],
  },
  es: {
    "business-plan-presentation":["Plantilla PowerPoint gratis de plan de negocio","Plan de negocio"], "startup-pitch-deck":["Plantilla gratis de pitch deck para startups","Pitch deck de startup"], "company-profile-presentation":["Plantilla PowerPoint gratis de perfil de empresa","Perfil de empresa"],
    "marketing-plan-presentation":["Plantilla PowerPoint gratis de plan de marketing","Plan de marketing"], "project-proposal-presentation":["Plantilla PowerPoint gratis de propuesta de proyecto","Propuesta de proyecto"], "sales-report-presentation":["Plantilla PowerPoint gratis de informe de ventas","Informe de ventas"],
    "lesson-plan-presentation":["Plantilla PowerPoint gratis de plan de clase","Plan de clase"], "thesis-defense-presentation":["Plantilla PowerPoint gratis para defensa de tesis","Defensa de tesis"], "clinical-case-presentation":["Plantilla PowerPoint gratis de caso clínico","Caso clínico"],
    "artificial-intelligence-presentation":["Plantilla PowerPoint gratis de inteligencia artificial","Inteligencia artificial"], "creative-portfolio-presentation":["Plantilla PowerPoint gratis de portafolio creativo","Portafolio creativo"], "product-roadmap-presentation":["Plantilla PowerPoint gratis de hoja de ruta de producto","Hoja de ruta de producto"],
  },
  ru: {
    "business-plan-presentation":["Бесплатный шаблон бизнес-плана PowerPoint","Бизнес-план"], "startup-pitch-deck":["Бесплатный шаблон питч-дека стартапа","Питч-дек стартапа"], "company-profile-presentation":["Бесплатный шаблон презентации компании","О компании"],
    "marketing-plan-presentation":["Бесплатный шаблон маркетингового плана PowerPoint","Маркетинговый план"], "project-proposal-presentation":["Бесплатный шаблон проектного предложения PowerPoint","Проектное предложение"], "sales-report-presentation":["Бесплатный шаблон отчёта о продажах PowerPoint","Отчёт о продажах"],
    "lesson-plan-presentation":["Бесплатный шаблон плана урока PowerPoint","План урока"], "thesis-defense-presentation":["Бесплатный шаблон защиты диссертации PowerPoint","Защита диссертации"], "clinical-case-presentation":["Бесплатный шаблон клинического случая PowerPoint","Клинический случай"],
    "artificial-intelligence-presentation":["Бесплатный шаблон PowerPoint об искусственном интеллекте","Искусственный интеллект"], "creative-portfolio-presentation":["Бесплатный шаблон творческого портфолио PowerPoint","Творческое портфолио"], "product-roadmap-presentation":["Бесплатный шаблон дорожной карты продукта PowerPoint","Дорожная карта продукта"],
  },
};

export function localizedTemplateName(template: PptTemplate, locale: Locale) {
  const names = localizedNames[locale]?.[template.slug];
  return { name: names?.[0] ?? template.name, shortName: names?.[1] ?? template.shortName };
}

export function localizedCategoryName(category: TemplateCategory, locale: Locale) {
  const templateSlug = `${category.slug}-presentation`;
  const exceptions: Record<string, string> = { "business-plan": "business-plan-presentation", "pitch-deck": "startup-pitch-deck", "company-profile": "company-profile-presentation", education: "lesson-plan-presentation", medical: "clinical-case-presentation", portfolio: "creative-portfolio-presentation" };
  return localizedNames[locale]?.[exceptions[category.slug] ?? templateSlug]?.[1] ?? category.name;
}
