import type { PptTemplate } from "@/lib/templates";

export const dailyTemplates: PptTemplate[] = [
  {
    slug: "vintage-small-business-plan",
    name: "Free Vintage Small Business Plan PowerPoint Template",
    shortName: "Vintage Small Business Plan",
    category: "Business Plan",
    categorySlug: "business-plan",
    description: "An editorial small business plan template for presenting a practical offer, local market, operating model, funding needs, and first-year priorities.",
    longDescription: "This free vintage small business plan PowerPoint template gives founders a compact structure for turning a grounded idea into a credible operating plan. Eight editable slides cover the purpose, customer need, offer, local market, revenue model, operations, funding, and first-year milestones. Its original archival visual system uses ivory paper, navy dossier bands, numbered file tabs, and red decision marks made entirely with native PowerPoint shapes. No book illustrations, source typography, or page compositions are reused.",
    accent: "B54A3A", dark: "172D45", soft: "F1E7D2",
    tags: ["Small business plan", "Vintage", "Entrepreneur", "16:9"],
    slides: [
      { eyebrow: "SMALL BUSINESS PLAN · 2026", title: "A neighborhood service built for dependable growth", body: "A practical plan connecting customer need, operating discipline, and a focused first year." },
      { eyebrow: "01 · PURPOSE", title: "Begin with the change the business exists to make", body: "State the customer, recurring problem, useful promise, and reason this team can deliver it.", stat: "1 promise" },
      { eyebrow: "02 · CUSTOMER", title: "Serve one reachable group exceptionally well", body: "Define where customers are, what triggers demand, what they value, and what they choose today." },
      { eyebrow: "03 · OFFER", title: "Turn expertise into three simple packages", body: "Make scope, outcome, timing, and price easy to understand before adding optional services." },
      { eyebrow: "04 · MARKET", title: "Size the opportunity from the ground up", body: "Use reachable locations, buyer frequency, conversion assumptions, and realistic capacity.", stat: "2,400" },
      { eyebrow: "05 · OPERATIONS", title: "Design the week before scaling the year", body: "Map demand, staffing, suppliers, quality checks, and the constraints that protect delivery." },
      { eyebrow: "06 · FUNDING", title: "Connect every dollar to a measurable milestone", body: "Separate setup, working capital, contingency, and the evidence each investment should unlock.", stat: "$65K" },
      { eyebrow: "07 · YEAR ONE", title: "Build repeatability before expanding", body: "Set quarterly milestones for customers, quality, cash, capacity, and the next review decision." },
    ],
    included: ["Plan cover", "Business purpose", "Target customer", "Offer design", "Local market", "Operating model", "Funding plan", "First-year milestones"],
    bestFor: ["Local service businesses", "Independent founders", "Loan conversations", "Small business planning"],
  },
  {
    slug: "retail-startup-pitch-deck",
    name: "Free Retail Startup Pitch Deck PowerPoint Template",
    shortName: "Retail Startup Pitch Deck",
    category: "Startup Pitch Deck",
    categorySlug: "pitch-deck",
    description: "A retail-focused pitch deck for presenting customer behavior, store concept, unit economics, traction, expansion logic, and a clear funding ask.",
    longDescription: "This free retail startup pitch deck PowerPoint template is organized around the evidence investors need to understand a physical or omnichannel concept. It moves from the shopping tension and retail promise to store experience, customer proof, unit economics, expansion model, defensibility, and use of funds. The original shelf-system design uses moss green, sand, cream, price-label geometry, and modular product bays without copying photography, illustrations, or layouts from the reference.",
    accent: "7DA33C", dark: "24352D", soft: "EEE5CF",
    tags: ["Retail startup", "Pitch deck", "Fundraising", "16:9"],
    slides: [
      { eyebrow: "RETAIL STARTUP · SEED", title: "Make considered shopping feel effortless", body: "A focused retail concept built around trust, discovery, and repeat purchase." },
      { eyebrow: "01 · TENSION", title: "Choice is abundant, but confidence is scarce", body: "Show the customer moment, current compromise, purchase frequency, and cost of uncertainty.", stat: "47%" },
      { eyebrow: "02 · CONCEPT", title: "Curate fewer products around one useful promise", body: "Explain assortment rules, service layer, physical experience, and the reason customers return." },
      { eyebrow: "03 · EXPERIENCE", title: "Every touchpoint reduces one purchase barrier", body: "Connect discovery, evaluation, checkout, fulfillment, and post-purchase support." },
      { eyebrow: "04 · PROOF", title: "Early stores show repeatable demand", body: "Present cohorts, repeat rate, basket growth, referrals, and verified customer feedback.", stat: "38%" },
      { eyebrow: "05 · ECONOMICS", title: "Store contribution improves with local density", body: "Show average order value, margin, labor, occupancy, payback, and sensitivity ranges." },
      { eyebrow: "06 · EXPANSION", title: "Grow through clusters, not isolated locations", body: "Sequence neighborhoods using demand signals, logistics reach, hiring, and brand awareness.", stat: "4 clusters" },
      { eyebrow: "07 · ASK", title: "Fund the proof for a repeatable second market", body: "State capital, runway, location milestones, team needs, and the evidence required for expansion." },
    ],
    included: ["Pitch cover", "Customer tension", "Retail concept", "Store journey", "Traction", "Unit economics", "Expansion model", "Funding ask"],
    bestFor: ["Retail founders", "Consumer startups", "Omnichannel concepts", "Seed fundraising"],
  },
  {
    slug: "modern-company-overview-presentation",
    name: "Free Modern Company Overview PowerPoint Template",
    shortName: "Modern Company Overview",
    category: "Company Profile",
    categorySlug: "company-profile",
    description: "A bold company overview template for communicating identity, capabilities, operating footprint, customer evidence, culture, and partnership opportunities.",
    longDescription: "This free modern company overview PowerPoint template turns a corporate introduction into a concise evidence-led story. Eight slides cover the company promise, key facts, capabilities, operating footprint, delivery model, customer proof, culture, and next conversation. The original brand-stamp visual system combines signal red, cream, black, oversized registration marks, and clean modular panels. It avoids the source template's icons, illustrations, slide arrangements, and supplied copy.",
    accent: "E44535", dark: "202020", soft: "F3EBDD",
    tags: ["Company overview", "Corporate profile", "Red", "16:9"],
    slides: [
      { eyebrow: "COMPANY OVERVIEW · 2026", title: "Built to make complex delivery feel dependable", body: "A concise introduction to our purpose, practice, proof, and people." },
      { eyebrow: "01 · IDENTITY", title: "One promise connects every part of the company", body: "Explain who you serve, what outcome you own, and the standards that make it credible.", stat: "12 years" },
      { eyebrow: "02 · SCALE", title: "A focused footprint with room to respond", body: "Present locations, customers, disciplines, capacity, and the operating facts that matter." },
      { eyebrow: "03 · CAPABILITIES", title: "Capabilities organized around customer outcomes", body: "Group expertise into a few offers with clear ownership instead of a long service inventory." },
      { eyebrow: "04 · DELIVERY", title: "Senior judgment stays close to the work", body: "Show the path from diagnosis and design through delivery, assurance, and improvement.", stat: "4 stages" },
      { eyebrow: "05 · PROOF", title: "Evidence turns claims into confidence", body: "Use a verified baseline, intervention, result, measurement window, and customer context." },
      { eyebrow: "06 · CULTURE", title: "The operating principles customers experience", body: "Connect internal behaviors to quality, responsiveness, transparency, and long-term value." },
      { eyebrow: "07 · PARTNER", title: "Start with one decision worth improving", body: "Close with the right first engagement, named owner, timing, and preparation needed." },
    ],
    included: ["Overview cover", "Company identity", "At-a-glance scale", "Capabilities", "Delivery model", "Customer proof", "Culture", "Partnership CTA"],
    bestFor: ["Corporate introductions", "Partner meetings", "Sales credentials", "Recruitment presentations"],
  },
  {
    slug: "campaign-marketing-plan-presentation",
    name: "Free Campaign Marketing Plan PowerPoint Template",
    shortName: "Campaign Marketing Plan",
    category: "Marketing Plan",
    categorySlug: "marketing",
    description: "A campaign marketing plan template for aligning the brief, audience tension, creative platform, channel roles, flighting, budget, and measurement.",
    longDescription: "This free campaign marketing plan PowerPoint template helps teams turn a strategy into one coherent launch. It covers the commercial brief, audience tension, message hierarchy, creative platform, channel roles, campaign flighting, budget, and measurement plan. The original poster-strip design uses cobalt, vermilion, pale gray, oversized type, and rhythmic campaign bands created from native shapes. It does not reproduce watercolor assets, source graphics, icons, or slide compositions.",
    accent: "3157D5", dark: "1D2130", soft: "E9EDF5",
    tags: ["Campaign plan", "Marketing strategy", "Launch", "16:9"],
    slides: [
      { eyebrow: "CAMPAIGN PLAN · LAUNCH", title: "One idea, expressed with disciplined variety", body: "A measurable campaign system connecting audience tension to channel action." },
      { eyebrow: "01 · BRIEF", title: "Define the commercial move before the creative task", body: "Name the behavior, business value, timing, constraints, and evidence the campaign must create.", stat: "+18%" },
      { eyebrow: "02 · AUDIENCE", title: "Find the tension that makes the message relevant", body: "Describe the situation, motivation, barrier, current workaround, and language customers use." },
      { eyebrow: "03 · MESSAGE", title: "Build a hierarchy the audience can remember", body: "Separate the central promise, reasons to believe, useful detail, and required action." },
      { eyebrow: "04 · PLATFORM", title: "Create a campaign idea that can travel", body: "Set the recurring thought, visual behavior, tone, and boundaries for channel adaptation.", stat: "1 idea" },
      { eyebrow: "05 · CHANNELS", title: "Give every channel a specific job", body: "Assign attention, education, capture, conversion, and retention roles before choosing formats." },
      { eyebrow: "06 · FLIGHTING", title: "Sequence learning, launch, and reinforcement", body: "Plan moments, dependencies, owners, stop rules, and the transition between campaign phases." },
      { eyebrow: "07 · MEASUREMENT", title: "Link every signal to a decision", body: "Track reach quality, response, conversion, incrementality, payback, and next investment." },
    ],
    included: ["Campaign cover", "Commercial brief", "Audience tension", "Message hierarchy", "Creative platform", "Channel roles", "Campaign flighting", "Measurement plan"],
    bestFor: ["Product launches", "Brand campaigns", "Agency proposals", "Integrated marketing plans"],
  },
  {
    slug: "blueprint-project-proposal",
    name: "Free Blueprint Project Proposal PowerPoint Template",
    shortName: "Blueprint Project Proposal",
    category: "Project Proposal",
    categorySlug: "project-proposal",
    description: "A blueprint-style project proposal for defining the case for change, target state, workstreams, deliverables, schedule, controls, and approval.",
    longDescription: "This free blueprint project proposal PowerPoint template presents delivery as a system that can be inspected before approval. Eight slides clarify the case for change, target state, design principles, workstreams, deliverables, milestone schedule, governance, and decision request. The original technical drawing language uses deep blue, cyan construction lines, coordinate marks, and modular specifications made with editable PowerPoint shapes; no source layouts or assets are reused.",
    accent: "43D8E8", dark: "12345A", soft: "DCEEF2",
    tags: ["Project proposal", "Blueprint", "Consulting", "16:9"],
    slides: [
      { eyebrow: "PROJECT BLUEPRINT · V1", title: "Design the result before committing the build", body: "A proposal that makes outcomes, boundaries, delivery, and controls inspectable." },
      { eyebrow: "01 · CASE", title: "The current system creates three avoidable costs", body: "Quantify delay, rework, risk, and the trigger that makes action necessary now.", stat: "3 costs" },
      { eyebrow: "02 · TARGET", title: "Describe the future state in observable terms", body: "Define what users can do, how work flows, which measures improve, and what remains unchanged." },
      { eyebrow: "03 · PRINCIPLES", title: "Use design rules to prevent local optimization", body: "Set decision principles for simplicity, ownership, interoperability, safety, and evidence." },
      { eyebrow: "04 · WORKSTREAMS", title: "Separate work without fragmenting accountability", body: "Show connected workstreams, owners, interfaces, deliverables, and shared decision points.", stat: "4 streams" },
      { eyebrow: "05 · SCHEDULE", title: "Use milestones as evidence gates", body: "Sequence discovery, prototype, pilot, migration, and review around explicit acceptance criteria." },
      { eyebrow: "06 · CONTROLS", title: "Make risk visible before it becomes delay", body: "Assign dependencies, assumptions, risk indicators, mitigations, escalation, and governance." },
      { eyebrow: "07 · DECISION", title: "Approve the first controlled commitment", body: "State scope, investment, sponsor, start date, and the evidence required for the next gate." },
    ],
    included: ["Proposal cover", "Case for change", "Target state", "Design principles", "Workstreams", "Milestone schedule", "Governance", "Approval request"],
    bestFor: ["Technology proposals", "Transformation programs", "Consulting projects", "Implementation planning"],
  },
  {
    slug: "sales-performance-review-presentation",
    name: "Free Sales Performance Review PowerPoint Template",
    shortName: "Sales Performance Review",
    category: "Sales Report",
    categorySlug: "sales-report",
    description: "A clear sales performance review for explaining target attainment, revenue mix, conversion, pipeline quality, segment movement, forecast, and commitments.",
    longDescription: "This free sales performance review PowerPoint template turns a recurring report into a decision meeting. Its eight slides cover headline performance, revenue bridge, conversion, pipeline quality, segment movement, forecast confidence, coaching focus, and owned commitments. The original ticker design uses cream, indigo, coral, fine rule lines, and compact numerical ribbons. Every chart is built from native shapes rather than copied source lines, circles, or dashboards.",
    accent: "EF654C", dark: "29345F", soft: "F5ECD8",
    tags: ["Sales performance", "Revenue review", "Forecast", "16:9"],
    slides: [
      { eyebrow: "SALES PERFORMANCE · Q3", title: "A strong quarter with one quality gap", body: "Performance, conversion, pipeline, forecast confidence, and the commitments ahead." },
      { eyebrow: "01 · ATTAINMENT", title: "Revenue reached plan with uneven contribution", body: "Compare actual, target, prior period, and mix before discussing the headline result.", stat: "103%" },
      { eyebrow: "02 · BRIDGE", title: "Expansion offset slower new-logo growth", body: "Separate new, expansion, contraction, churn, timing, and one-off effects." },
      { eyebrow: "03 · CONVERSION", title: "Discovery improved while proposal discipline slipped", body: "Show stage volume, conversion, age, loss reason, and the behavior behind the change." },
      { eyebrow: "04 · PIPELINE", title: "Coverage is sufficient but timing is concentrated", body: "Explain quality by stage, source, size, age, concentration, and verified next action.", stat: "3.2×" },
      { eyebrow: "05 · SEGMENTS", title: "Mid-market leads on speed and expansion", body: "Use consistent measures to compare segment economics, cycle, conversion, and retention." },
      { eyebrow: "06 · FORECAST", title: "Confidence depends on two customer decisions", body: "Present commit, best case, risk range, assumptions, and leading indicators." },
      { eyebrow: "07 · COMMITMENTS", title: "Turn insight into three coached behaviors", body: "Assign owners, observable actions, expected signals, and the next review date." },
    ],
    included: ["Review cover", "Target attainment", "Revenue bridge", "Conversion", "Pipeline quality", "Segment performance", "Forecast", "Commitments"],
    bestFor: ["Monthly sales reviews", "Revenue operations", "Manager coaching", "Executive forecasting"],
  },
  {
    slug: "yellow-lesson-plan-presentation",
    name: "Free Yellow Lesson Plan PowerPoint Template",
    shortName: "Yellow Lesson Plan",
    category: "Lesson Plan",
    categorySlug: "education",
    description: "A bright lesson plan template for sequencing an essential question, objectives, instruction, modeling, practice, assessment, and reflection.",
    longDescription: "This free yellow lesson plan PowerPoint template gives teachers an energetic but orderly classroom sequence. Eight editable slides move from the essential question and objectives to activation, direct instruction, modeling, guided practice, assessment, and reflection. The original whiteboard visual system combines sunflower yellow, sky blue, ink, timetable rails, and rounded activity tiles. It does not use the source planner's illustrations, frames, animations, fonts, or layouts.",
    accent: "F4C542", dark: "24354A", soft: "E4F1F7",
    tags: ["Lesson plan", "Teacher", "Yellow", "16:9"],
    slides: [
      { eyebrow: "LESSON PLAN · 50 MIN", title: "How does evidence change an explanation?", body: "Notice, model, practise, check, and reflect through one coherent learning sequence." },
      { eyebrow: "01 · QUESTION", title: "Open with a question worth revisiting", body: "Use an accessible puzzle that exposes prior ideas and creates a reason to learn.", stat: "5 min" },
      { eyebrow: "02 · OBJECTIVES", title: "Make success visible to learners", body: "Describe what students will understand, produce, and explain by the end." },
      { eyebrow: "03 · ACTIVATE", title: "Surface prior knowledge before adding content", body: "Give every learner time to retrieve, predict, compare, and share a starting idea." },
      { eyebrow: "04 · MODEL", title: "Reveal the decisions inside the example", body: "Think aloud through the process, name cues, and contrast one common misconception.", stat: "3 cues" },
      { eyebrow: "05 · PRACTICE", title: "Release responsibility in deliberate steps", body: "Move from whole-class response to pairs and independent work with one success criterion." },
      { eyebrow: "06 · CHECK", title: "Use evidence to choose the next teaching move", body: "Ask one diagnostic question, group responses, and plan immediate feedback." },
      { eyebrow: "07 · REFLECT", title: "Return to the opening question", body: "Let learners revise their explanation, name the evidence used, and preview transfer." },
    ],
    included: ["Lesson cover", "Essential question", "Learning objectives", "Prior knowledge", "Teacher model", "Guided practice", "Assessment", "Reflection"],
    bestFor: ["Secondary classrooms", "Teacher training", "Online lessons", "Workshop facilitation"],
  },
  {
    slug: "green-thesis-defense-presentation",
    name: "Free Green Thesis Defense PowerPoint Template",
    shortName: "Green Thesis Defense",
    category: "Thesis Defense",
    categorySlug: "thesis-defense",
    description: "A restrained green thesis defense template for presenting the central claim, research gap, design, results, interpretation, contribution, and limitations.",
    longDescription: "This free green thesis defense PowerPoint template is designed around a committee's need to trace claim to evidence. Eight slides cover the thesis, research gap, conceptual frame, study design, primary result, interpretation, contribution, and limitations. Its original margin-note design combines forest green, sage, parchment, brown annotations, and academic rule lines. It avoids the reference's charts, frames, photography, typeface, and slide compositions.",
    accent: "52745B", dark: "3E302B", soft: "E5E8D5",
    tags: ["Thesis defense", "Academic", "Green", "16:9"],
    slides: [
      { eyebrow: "THESIS DEFENSE · 2026", title: "Coordination improves when evidence has an owner", body: "A study of decision traceability, shared context, and accountable interpretation." },
      { eyebrow: "01 · THESIS", title: "The central claim in one testable sentence", body: "Define the relationship, population, setting, and scope without overstating the evidence.", stat: "1 claim" },
      { eyebrow: "02 · GAP", title: "Prior work describes access but not ownership", body: "Synthesize what is known, where findings conflict, and the precise unanswered question." },
      { eyebrow: "03 · FRAME", title: "Three mechanisms connect context to action", body: "Explain the conceptual model, propositions, boundaries, and observable implications." },
      { eyebrow: "04 · DESIGN", title: "A longitudinal field study tests the mechanism", body: "Describe sampling, measures, procedure, comparison, ethics, and analysis choices.", stat: "n=216" },
      { eyebrow: "05 · RESULT", title: "Named ownership improved decision traceability", body: "Present magnitude, uncertainty, robustness, and the distinction between planned and exploratory findings." },
      { eyebrow: "06 · CONTRIBUTION", title: "The study connects information design to accountability", body: "State the theoretical addition, practical implication, and what remains unresolved." },
      { eyebrow: "07 · LIMITS", title: "Interpret the effect within its boundaries", body: "Name setting, selection, measurement, duration, and the next study needed." },
    ],
    included: ["Defense cover", "Central thesis", "Research gap", "Conceptual frame", "Study design", "Results", "Contribution", "Limitations"],
    bestFor: ["PhD defenses", "Master's defenses", "Research seminars", "Academic proposals"],
  },
  {
    slug: "modern-clinical-case-presentation",
    name: "Free Modern Clinical Case PowerPoint Template",
    shortName: "Modern Clinical Case",
    category: "Clinical Case",
    categorySlug: "medical",
    description: "A modern clinical case template for presenting de-identified chronology, findings, diagnostic reasoning, management decisions, outcome, and learning points.",
    longDescription: "This free modern clinical case PowerPoint template organizes complex clinical reasoning without exposing identifying data. Eight slides cover the presenting concern, chronology, focused findings, investigations, differential, management, outcome, and learning points. The original pulse-track system uses deep teal, blue, lavender, layered evidence bands, and simple status markers. No patient imagery, medical illustration, source gradients, icons, or layouts are reused.",
    accent: "3479D3", dark: "173F4B", soft: "E7EDF8",
    tags: ["Clinical case", "Medical education", "Case report", "16:9"],
    slides: [
      { eyebrow: "CLINICAL CASE · DE-IDENTIFIED", title: "Reasoning through a changing presentation", body: "Chronology, findings, differential, decisions, outcome, and transferable learning." },
      { eyebrow: "01 · CONCERN", title: "Begin with the change that prompted evaluation", body: "Summarize onset, trajectory, severity, context, and relevant negative information.", stat: "Day 0" },
      { eyebrow: "02 · CHRONOLOGY", title: "Sequence events before interpreting them", body: "Separate symptoms, observations, interventions, tests, and responses on one time axis." },
      { eyebrow: "03 · FINDINGS", title: "Prioritize findings that change probability", body: "Present focused examination, vital trends, red flags, and meaningful negatives." },
      { eyebrow: "04 · TESTS", title: "Show what each investigation contributed", body: "Include indication, timing, reference, result, uncertainty, and effect on reasoning.", stat: "5 tests" },
      { eyebrow: "05 · DIFFERENTIAL", title: "Compare support, conflict, urgency, and consequence", body: "Make competing explanations visible and explain why the working assessment changed." },
      { eyebrow: "06 · MANAGEMENT", title: "Tie each action to a clinical objective", body: "Document treatment, monitoring, shared decisions, escalation thresholds, and response." },
      { eyebrow: "07 · LEARNING", title: "Separate case-specific outcome from general lesson", body: "Close with follow-up, limitations, safety considerations, and three teaching points." },
    ],
    included: ["Case cover", "Presenting concern", "Chronology", "Focused findings", "Investigations", "Differential", "Management", "Learning points"],
    bestFor: ["Clinical teaching", "Case conferences", "Residency presentations", "Quality reviews"],
  },
  {
    slug: "ai-strategy-presentation",
    name: "Free AI Strategy PowerPoint Template",
    shortName: "AI Strategy",
    category: "AI & Technology",
    categorySlug: "artificial-intelligence",
    description: "An AI strategy template for aligning business outcomes, use-case portfolio, operating model, evaluation, data readiness, controls, adoption, and roadmap.",
    longDescription: "This free AI strategy PowerPoint template helps leadership teams discuss artificial intelligence as an operating choice rather than a technology spectacle. Eight slides cover the strategic outcome, use-case portfolio, operating model, evaluation, data readiness, controls, adoption, and roadmap. The original console visual language uses near-black, terminal green, magenta signals, system labels, and modular status panels. It does not copy the source's brain imagery, robots, three-stage diagram, icons, or text.",
    accent: "70E59B", dark: "111516", soft: "252B2B",
    tags: ["AI strategy", "Artificial intelligence", "Leadership", "16:9"],
    slides: [
      { eyebrow: "AI STRATEGY · OPERATING SYSTEM", title: "Turn useful intelligence into reliable work", body: "A strategy connecting outcomes, use cases, capabilities, controls, adoption, and evidence." },
      { eyebrow: "01 · OUTCOME", title: "Start with decisions worth improving", body: "Define the user, decision, friction, economic value, acceptable risk, and measurable change.", stat: "4 outcomes" },
      { eyebrow: "02 · PORTFOLIO", title: "Balance value, feasibility, and consequence", body: "Compare use cases using common evidence instead of prioritizing the most impressive demo." },
      { eyebrow: "03 · MODEL", title: "Make ownership explicit across the lifecycle", body: "Assign product, domain, data, engineering, risk, and operational responsibilities." },
      { eyebrow: "04 · EVALUATION", title: "Test representative work before broad access", body: "Set baselines, datasets, failure categories, thresholds, human review, and monitoring.", stat: "6 gates" },
      { eyebrow: "05 · DATA", title: "Improve context quality before model complexity", body: "Address access, permissions, freshness, provenance, structure, retention, and feedback." },
      { eyebrow: "06 · CONTROLS", title: "Match safeguards to consequence", body: "Design approval, disclosure, isolation, escalation, audit, rollback, and incident response." },
      { eyebrow: "07 · ADOPTION", title: "Scale workflows only after evidence", body: "Sequence pilot groups, training, support, behavior measures, economics, and expansion gates." },
    ],
    included: ["Strategy cover", "Business outcomes", "Use-case portfolio", "Operating model", "Evaluation", "Data readiness", "Controls", "Adoption roadmap"],
    bestFor: ["Executive AI strategy", "AI transformation", "Technology roadmaps", "Governance discussions"],
  },
  {
    slug: "y2k-creative-portfolio",
    name: "Free Y2K Creative Portfolio PowerPoint Template",
    shortName: "Y2K Creative Portfolio",
    category: "Creative Portfolio",
    categorySlug: "portfolio",
    description: "A bright Y2K-inspired portfolio template for showcasing a creative thesis, selected projects, process, experiments, outcomes, capabilities, and contact details.",
    longDescription: "This free Y2K creative portfolio PowerPoint template offers an energetic alternative to restrained editorial portfolios. Eight slides cover a creative thesis, project index, flagship case study, process, experiments, outcomes, capabilities, and contact. Its original pixel-window system combines hot pink, cool gray, cyan, modular interface frames, and large typographic labels built from native shapes. It excludes the reference's photographs, neon assets, supplied frames, fonts, and compositions.",
    accent: "F04F9B", dark: "34333A", soft: "DDE5E8",
    tags: ["Y2K portfolio", "Creative portfolio", "Design", "16:9"],
    slides: [
      { eyebrow: "CREATIVE PORTFOLIO · 2026", title: "Clear systems with a little productive friction", body: "Selected identity, digital, editorial, and experimental work." },
      { eyebrow: "01 · THESIS", title: "Distinctive work begins with a useful point of view", body: "State the problems you choose, principles you apply, and value you aim to create.", stat: "1 thesis" },
      { eyebrow: "02 · INDEX", title: "Curate projects around the audience", body: "Select a small set that demonstrates relevant range, depth, constraints, and outcomes." },
      { eyebrow: "03 · CASE", title: "A new identity made a complex offer legible", body: "Show context, brief, constraint, exploration, decision, delivered system, and evidence." },
      { eyebrow: "04 · PROCESS", title: "Structure creates room for surprise", body: "Explain how research, framing, prototypes, critique, testing, and refinement connect.", stat: "6 moves" },
      { eyebrow: "05 · EXPERIMENTS", title: "Use side projects to test new visual behavior", body: "Present the question, boundary, iteration, learning, and influence on client work." },
      { eyebrow: "06 · OUTCOMES", title: "Connect craft to comprehension and action", body: "Use verified measures, feedback, adoption, efficiency, or recognition with context." },
      { eyebrow: "07 · CONTACT", title: "Make the next collaboration easy to begin", body: "Share fit, availability, working mode, contact information, and one specific invitation." },
    ],
    included: ["Portfolio cover", "Creative thesis", "Project index", "Case study", "Process", "Experiments", "Outcomes", "Contact"],
    bestFor: ["Graphic designers", "Digital portfolios", "Creative studios", "Student showcases"],
  },
  {
    slug: "quarterly-product-roadmap",
    name: "Free Quarterly Product Roadmap PowerPoint Template",
    shortName: "Quarterly Product Roadmap",
    category: "Product Roadmap",
    categorySlug: "product-roadmap",
    description: "A quarterly product roadmap template for connecting strategic outcomes, evidence, bets, releases, dependencies, capacity, success measures, and review gates.",
    longDescription: "This free quarterly product roadmap PowerPoint template helps product teams communicate direction without presenting uncertain dates as promises. Eight editable slides cover the outcome, evidence, strategic bets, quarterly releases, dependencies, capacity, measures, and review gates. The original terrain-map visual system combines forest green, lime, navy, cream, contour rings, and confidence markers. It avoids copied timelines, icons, charts, fonts, and source layouts.",
    accent: "B6E05A", dark: "18362F", soft: "E8E5CF",
    tags: ["Quarterly roadmap", "Product strategy", "Planning", "16:9"],
    slides: [
      { eyebrow: "PRODUCT ROADMAP · Q4–Q2", title: "A route from first value to durable habit", body: "Outcomes, evidence, strategic bets, releases, constraints, and review gates." },
      { eyebrow: "01 · OUTCOME", title: "Anchor the roadmap in changed customer behavior", body: "State who succeeds, what they can do, how quickly, and why the outcome matters.", stat: "< 3 min" },
      { eyebrow: "02 · EVIDENCE", title: "Use multiple signals to shape each bet", body: "Combine behavior, research, support, commercial context, reliability, and technical learning." },
      { eyebrow: "03 · BETS", title: "Name the assumptions behind the investment", body: "Describe expected outcome, user, mechanism, evidence, confidence, and stop condition." },
      { eyebrow: "04 · QUARTERS", title: "Sequence releases around learning", body: "Show what becomes available, to whom, what it tests, and what unlocks the next horizon.", stat: "3 horizons" },
      { eyebrow: "05 · DEPENDENCIES", title: "Expose the paths that can change timing", body: "Connect platform, data, policy, research, commercial, and staffing constraints to owners." },
      { eyebrow: "06 · CAPACITY", title: "Fund reliability and discovery alongside delivery", body: "Make allocation, interrupt budget, maintenance, and discovery capacity visible." },
      { eyebrow: "07 · REVIEW", title: "Use roadmap reviews to change decisions", body: "Compare expected and observed signals, update confidence, and record the next commitment." },
    ],
    included: ["Roadmap cover", "Product outcome", "Evidence", "Strategic bets", "Quarterly releases", "Dependencies", "Capacity", "Review gates"],
    bestFor: ["Quarterly planning", "Product leadership", "Cross-functional alignment", "Stakeholder updates"],
  },
];
