import type { Metadata } from "next";
import Link from "next/link";
import { Check, FileDown, LayoutTemplate, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { Header } from "@/components/header";
import { TemplateActions } from "@/components/template-actions";
import { TemplateCard } from "@/components/template-card";
import { TemplateGallery } from "@/components/template-gallery";
import { SITE_URL } from "@/lib/site";
import { getTemplate, getTemplateCategory, templateCategories, templates } from "@/lib/templates";

export function generateStaticParams() { return [...templateCategories.map(({ slug }) => ({ slug })), ...templates.map(({ slug }) => ({ slug }))]; }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const slug = (await params).slug;
  const category = getTemplateCategory(slug);
  if (category) return { title: `Free ${category.name} PowerPoint Template | FreeAIPPT`, description: `${category.description} Download one original, editable 16:9 PPTX without signing up.`, keywords: [category.searchIntent, `${category.shortName.toLowerCase()} ppt template free download`, `editable ${category.shortName.toLowerCase()} presentation`], alternates: { canonical: `/templates/${category.slug}` }, openGraph: { title: `Free ${category.name} PowerPoint Template`, description: category.description, type: "website", url: `/templates/${category.slug}` } };
  const template = getTemplate(slug);
  if (!template) return {};
  return { title: `${template.name}: Free Download | FreeAIPPT`, description: template.description, keywords: [`${template.shortName.toLowerCase()} ppt template free`, `${template.shortName.toLowerCase()} powerpoint template`, "free editable ppt template"], alternates: { canonical: `/templates/${template.slug}` }, openGraph: { title: template.name, description: template.description, type: "article", url: `/templates/${template.slug}` } };
}

export default async function TemplatePage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug;
  const category = getTemplateCategory(slug);
  if (category) {
    const categoryTemplates = templates.filter((item) => item.categorySlug === category.slug);
    const jsonLd = { "@context": "https://schema.org", "@type": "CollectionPage", name: `Free ${category.name} PowerPoint Templates`, description: category.description, url: `${SITE_URL}/templates/${category.slug}`, mainEntity: { "@type": "ItemList", numberOfItems: categoryTemplates.length, itemListElement: categoryTemplates.map((template, index) => ({ "@type": "ListItem", position: index + 1, url: `${SITE_URL}/templates/${template.slug}`, name: template.name })) } };
    return <main><Header /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><section className="category-hero"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/templates">Templates</Link><span>/</span><span>{category.name}</span></nav><span className="article-kicker"><LayoutTemplate size={14} /> {category.name.toUpperCase()} TEMPLATE</span><h1>Free {category.name}<br /><em>PowerPoint template</em></h1><p>{category.description}</p></section><section className="template-library"><div className="template-library-head"><div><span className="eyebrow">1 ORIGINAL TEMPLATE · FREE</span><h2>Start your {category.shortName.toLowerCase()} presentation</h2><p>Eight editable 16:9 layouts, built from scratch with native PowerPoint shapes and clear placeholder content.</p></div></div><div className="template-grid">{categoryTemplates.map((template) => <TemplateCard template={template} key={template.slug} />)}</div></section><section className="template-seo"><div><span className="eyebrow">A FOCUSED STARTING POINT</span><h2>How to use this {category.shortName.toLowerCase()} template</h2></div><div><p>{category.description} Begin by replacing the sample narrative with verified information, then remove any slide that does not help the audience make the intended decision.</p><p>The download is an original FreeAIPPT design made from editable text and native shapes. Change the colors and typography to fit your context, review spacing after editing, and test the final deck on the screen used for the presentation.</p></div></section></main>;
  }
  const template = getTemplate(slug);
  if (!template) notFound();
  const related = templates.filter((item) => item.slug !== template.slug).slice(0, 2);
  const faq = [{ q: `Is this ${template.shortName} PowerPoint template free?`, a: "Yes. You can download and use it in personal or commercial presentations without creating an account. You may not resell or redistribute the standalone template file." }, { q: "Can I edit every slide in PowerPoint?", a: "Yes. The text, shapes, colors, and layout elements are native editable PowerPoint objects. Sample facts and figures must be replaced with your own verified information." }, { q: "Does the template work in Google Slides and Keynote?", a: "Both applications can import PPTX files, but fonts and spacing can change. Review every slide after importing and before presenting." }];
  const jsonLd = [{ "@context": "https://schema.org", "@type": "CreativeWork", name: template.name, description: template.description, creator: { "@type": "Organization", name: "FreeAIPPT" }, isAccessibleForFree: true, inLanguage: "en", url: `${SITE_URL}/templates/${template.slug}`, license: `${SITE_URL}/templates/LICENSE.txt`, encoding: { "@type": "MediaObject", contentUrl: `${SITE_URL}/templates/files/${template.slug}.pptx`, encodingFormat: "application/vnd.openxmlformats-officedocument.presentationml.presentation" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "Templates", item: `${SITE_URL}/templates` }, { "@type": "ListItem", position: 3, name: template.name, item: `${SITE_URL}/templates/${template.slug}` }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.q, acceptedAnswer: { "@type": "Answer", text: item.a } })) }];
  return <main><Header /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><article className="template-detail"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/templates">Templates</Link><span>/</span><Link href={`/templates/${template.categorySlug}`}>{template.category}</Link><span>/</span><span>{template.shortName}</span></nav><header className="template-detail-head"><div><span className="article-kicker"><LayoutTemplate size={14} /> FREE EDITABLE POWERPOINT TEMPLATE</span><h1>{template.name}</h1><p>{template.description}</p><div className="template-tags">{template.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><TemplateActions slug={template.slug} /></header><section><div className="section-heading"><span>SLIDE PREVIEW</span><h2>Eight layouts included</h2><p>Click any slide to inspect it at a larger size.</p></div><TemplateGallery template={template} /></section><section className="template-info-grid"><div><span className="eyebrow">ABOUT THIS TEMPLATE</span><h2>A practical structure you can make your own</h2><p>{template.longDescription}</p><h3>Best for</h3><ul>{template.bestFor.map((item) => <li key={item}><Check />{item}</li>)}</ul></div><aside><h3>Template details</h3><dl><div><dt>Slides</dt><dd>8</dd></div><div><dt>Format</dt><dd>Editable PPTX</dd></div><div><dt>Ratio</dt><dd>16:9 widescreen</dd></div><div><dt>Language</dt><dd>English</dd></div><div><dt>Fonts</dt><dd>Aptos / Aptos Display</dd></div><div><dt>License</dt><dd>Personal &amp; commercial use</dd></div></dl><a href="/templates/LICENSE.txt" target="_blank"><ShieldCheck /> Read template license</a></aside></section><section className="included-section"><span className="eyebrow">WHAT&apos;S INCLUDED</span><h2>A complete eight-slide story</h2><div>{template.included.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div></section><section className="download-band"><FileDown /><div><h2>Ready to build your presentation?</h2><p>Download the editable file now, or use AI to adapt the structure to your content.</p></div><TemplateActions slug={template.slug} /></section><section><div className="section-heading"><span>MORE FREE TEMPLATES</span><h2>Related presentation templates</h2></div><div className="template-grid related">{related.map((item) => <TemplateCard template={item} key={item.slug} />)}</div></section><section id="faq"><div className="section-heading"><span>FAQ</span><h2>Frequently asked questions</h2></div><div className="faq-list">{faq.map((item) => <details key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></section></article></main>;
}
