import type { Metadata } from "next";
import Link from "next/link";
import { Check, FileDown, LayoutTemplate, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { Header } from "@/components/header";
import { TemplateActions } from "@/components/template-actions";
import { TemplateCard } from "@/components/template-card";
import { TemplateGallery } from "@/components/template-gallery";
import { languageAlternates } from "@/lib/i18n";
import { templateSeoCopy } from "@/lib/seo-i18n";
import { SITE_URL } from "@/lib/site";
import { getTemplate, getTemplateCategory, templateCategories, templates } from "@/lib/templates";

export function generateStaticParams() { return [...templateCategories.map(({ slug }) => ({ slug })), ...templates.map(({ slug }) => ({ slug }))]; }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const slug = (await params).slug;
  const category = getTemplateCategory(slug);
  if (category) {
    const route = `/templates/${category.slug}`;
    const title = `Free ${category.name} PowerPoint Templates | FreeAIPPT`;
    const description = `${category.description} Download original, editable 16:9 PPTX files without signing up.`;
    return { title, description, keywords: [category.searchIntent, `${category.shortName.toLowerCase()} ppt templates free download`, `editable ${category.shortName.toLowerCase()} presentations`], authors: [{ name: "FreeAIPPT", url: SITE_URL }], creator: "FreeAIPPT", publisher: "FreeAIPPT", alternates: { canonical: route, languages: { ...languageAlternates(route), "x-default": route } }, openGraph: { title, description, type: "website", url: route, siteName: "FreeAIPPT", locale: "en_US" }, twitter: { card: "summary", title, description } };
  }
  const template = getTemplate(slug);
  if (!template) return {};
  const route = `/templates/${template.slug}`;
  const title = `${template.name}: Free Download | FreeAIPPT`;
  const image = `/templates/previews/${template.slug}/01.jpg`;
  return { title, description: template.description, keywords: [`${template.shortName.toLowerCase()} ppt template free`, `${template.shortName.toLowerCase()} powerpoint template`, "free editable ppt template"], authors: [{ name: "FreeAIPPT", url: SITE_URL }], creator: "FreeAIPPT", publisher: "FreeAIPPT", alternates: { canonical: route, languages: { ...languageAlternates(route), "x-default": route } }, openGraph: { title, description: template.description, type: "website", url: route, siteName: "FreeAIPPT", locale: "en_US", images: [{ url: image, width: 1600, height: 900, alt: `${template.name} cover` }] }, twitter: { card: "summary_large_image", title, description: template.description, images: [image] } };
}

export default async function TemplatePage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug;
  const category = getTemplateCategory(slug);
  if (category) {
    const categoryTemplates = templates.filter((item) => item.categorySlug === category.slug);
    const jsonLd = { "@context": "https://schema.org", "@type": "CollectionPage", name: `Free ${category.name} PowerPoint Templates`, description: category.description, inLanguage: "en", url: `${SITE_URL}/templates/${category.slug}`, publisher: { "@id": `${SITE_URL}/#organization` }, mainEntity: { "@type": "ItemList", numberOfItems: categoryTemplates.length, itemListElement: categoryTemplates.map((template, index) => ({ "@type": "ListItem", position: index + 1, url: `${SITE_URL}/templates/${template.slug}`, name: template.name })) } };
    return <main><Header /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><section className="category-hero"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/templates">Templates</Link><span>/</span><span>{category.name}</span></nav><span className="article-kicker"><LayoutTemplate size={14} /> {category.name.toUpperCase()} TEMPLATES</span><h1>Free {category.name}<br /><em>PowerPoint templates</em></h1><p>{category.description}</p></section><section className="template-library"><div className="template-library-head"><div><span className="eyebrow">{categoryTemplates.length} ORIGINAL TEMPLATES · FREE</span><h2>Start your {category.shortName.toLowerCase()} presentation</h2><p>Every download contains eight editable 16:9 layouts, built from scratch with native PowerPoint shapes and clear placeholder content.</p></div></div><div className="template-grid">{categoryTemplates.map((template) => <TemplateCard template={template} key={template.slug} />)}</div></section><section className="template-seo"><div><span className="eyebrow">FOCUSED STARTING POINTS</span><h2>How to use these {category.shortName.toLowerCase()} templates</h2></div><div><p>{category.description} Begin by replacing the sample narrative with verified information, then remove any slide that does not help the audience make the intended decision.</p><p>Every download is an original FreeAIPPT design made from editable text and native shapes. Change the colors and typography to fit your context, review spacing after editing, and test the final deck on the screen used for the presentation.</p></div></section></main>;
  }
  const template = getTemplate(slug);
  if (!template) notFound();
  const seo = templateSeoCopy("en");
  const related = templates.filter((item) => item.slug !== template.slug).slice(0, 2);
  const faq = seo.faq(template.shortName);
  const jsonLd = [{ "@context": "https://schema.org", "@type": "CreativeWork", name: template.name, description: template.description, creator: { "@id": `${SITE_URL}/#organization` }, publisher: { "@id": `${SITE_URL}/#organization` }, copyrightHolder: { "@id": `${SITE_URL}/#organization` }, isAccessibleForFree: true, inLanguage: "en", mainEntityOfPage: `${SITE_URL}/templates/${template.slug}`, url: `${SITE_URL}/templates/${template.slug}`, license: `${SITE_URL}/templates/LICENSE.txt`, encoding: { "@type": "MediaObject", contentUrl: `${SITE_URL}/templates/files/${template.slug}.pptx`, encodingFormat: "application/vnd.openxmlformats-officedocument.presentationml.presentation" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "Templates", item: `${SITE_URL}/templates` }, { "@type": "ListItem", position: 3, name: template.category, item: `${SITE_URL}/templates/${template.categorySlug}` }, { "@type": "ListItem", position: 4, name: template.name, item: `${SITE_URL}/templates/${template.slug}` }] }, { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: "en", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.q, acceptedAnswer: { "@type": "Answer", text: item.a } })) }];
  return <main><Header /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><article className="template-detail"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/templates">Templates</Link><span>/</span><Link href={`/templates/${template.categorySlug}`}>{template.category}</Link><span>/</span><span>{template.shortName}</span></nav><header className="template-detail-head"><div><span className="article-kicker"><LayoutTemplate size={14} /> FREE EDITABLE POWERPOINT TEMPLATE</span><h1>{template.name}</h1><p>{template.description}</p><p className="template-byline">{seo.byline}</p><div className="template-tags">{template.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><TemplateActions slug={template.slug} /></header><section><div className="section-heading"><span>SLIDE PREVIEW</span><h2>Eight layouts included</h2><p>Click any slide to inspect it at a larger size.</p></div><TemplateGallery template={template} /></section><section className="template-info-grid"><div><span className="eyebrow">ABOUT THIS TEMPLATE</span><h2>A practical structure you can make your own</h2><p>{template.longDescription}</p><h3>Best for</h3><ul>{template.bestFor.map((item) => <li key={item}><Check />{item}</li>)}</ul></div><aside><h3>Template details</h3><dl><div><dt>Slides</dt><dd>8</dd></div><div><dt>Format</dt><dd>Editable PPTX</dd></div><div><dt>Ratio</dt><dd>16:9 widescreen</dd></div><div><dt>Language</dt><dd>English</dd></div><div><dt>Fonts</dt><dd>Aptos / Aptos Display</dd></div><div><dt>License</dt><dd>Personal &amp; commercial use</dd></div></dl><a href="/templates/LICENSE.txt" target="_blank"><ShieldCheck /> Read template license</a></aside></section><section className="template-provenance" data-testid={`template-${template.slug}-provenance`}><ShieldCheck /><div><span className="eyebrow">FreeAIPPT</span><h2>{seo.trustTitle}</h2><p>{seo.trustBody}</p></div></section><section className="included-section"><span className="eyebrow">WHAT&apos;S INCLUDED</span><h2>A complete eight-slide story</h2><div>{template.included.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div></section><section className="download-band"><FileDown /><div><h2>Ready to build your presentation?</h2><p>Download the editable file now, or use AI to adapt the structure to your content.</p></div><TemplateActions slug={template.slug} placement="footer" /></section><section><div className="section-heading"><span>MORE FREE TEMPLATES</span><h2>Related presentation templates</h2></div><div className="template-grid related">{related.map((item) => <TemplateCard template={item} key={item.slug} />)}</div></section><section id="faq"><div className="section-heading"><span>FAQ</span><h2>{seo.faqTitle}</h2></div><div className="faq-list">{faq.map((item) => <details key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></section></article></main>;
}
